### PR TITLE
JBTM-3528: Create release profile for lra-test-arquillian-extension

### PR DESCRIPTION
**Pull request by mayankkunwar**
https://issues.redhat.com/browse/JBTM-3528

LRA
JDK11

!MAIN !CORE !TOMCAT !AS_TESTS !RTS !JACOCO !XTS !QA_JTA !QA_JTS_JACORB !QA_JTS_JDKORB !QA_JTS_OPENJDKORB !PERF  !NO_WIN !DB_TESTS !mysql !db2 !postgres !oracle

### CODE REVIEW

**Comment by mmusgrov** [comment]
The JDK 11 failure looks like it may be https://issues.redhat.com/browse/JBTM-3526

**Review by ochaloup — COMMENTED** [review]
The changes seems fine to me and the CI errors do not seem to be connected to the fact of adding a new profile which is even not activated in CI tests.

The github actions fails with port binding error at one test

```
io.narayana.lra.coordinator.domain.model.LRATest.testNestedLRAChildCancelsEarly(io.narayana.lra.coordinator.domain.model.LRATest)
Error:    Run 1: LRATest.before:323 » Runtime java.net.BindException: Address already in use
```

and the failure on AMS CI seems unrelated as well

```
[ERROR] Tests run: 2, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 71.462 s <<< FAILURE! - in org.eclipse.microprofile.lra.tck.TckRecoveryTests
[ERROR] testCancelWhenParticipantIsUnavailable(org.eclipse.microprofile.lra.tck.TckRecoveryTests)  Time elapsed: 41.088 s  <<< FAILURE!
java.lang.AssertionError: 
Expecting the metric Compensated callback was called
Expected: a value equal to or greater than <1>
     but: <0> was less than <1>
	at org.eclipse.microprofile.lra.tck.TckRecoveryTests.assertMetricCallbackCalled(TckRecoveryTests.java:218)
	at org.eclipse.microprofile.lra.tck.TckRecoveryTests.testCancelWhenParticipantIsUnavailable(TckRecoveryTests.java:203)
```

**Review by ochaloup — APPROVED** [review]
Approving as it seems to be fine and the test failures are intermittent not related to this PR.

**Comment by mayankkunwar** [comment]
Thanks for the review

**Pull request merged**
