### PR TITLE
JBTM 3089 (LRA code improvements) and JBTM-3413 (close resources)

### PR DESCRIPTION
**Pull request by mmusgrov**
https://issues.redhat.com/browse/JBTM-3089 (LRA code improvements)
https://issues.redhat.com/browse/JBTM-3413 (Close JAX-RS message entity input streams)

LRA !CORE !TOMCAT !AS_TESTS !RTS !JACOCO !XTS !QA_JTA !QA_JTS_OPENJDKORB !PERFORMANCE !DB_TESTS !mysql !db2 !postgres !oracle

This is a non-functional change to improve the readability and maintainability.

### CODE REVIEW

**Comment by mmusgrov** [comment]
There is no reformatting involved (apart from the extra blank line after the SPDX id and in one or two other places, but minimal). That said I used Intelij warnings as my prompt in many places but those cover a lot more than just formatting. If you analyse each change on its own merit you should notice that they are improving the code and not reformatting it and that there is sufficient diversity in the change set that only an AI assistant would be able to duplicate that change set. We can pick on a random subset of the changes if you like and I will explain my justification for each of them, which ones in particular did you have in mind?

**Comment by marcosgopen** [comment]
Thanks Mike for your clarification. I said formatting because I can see some commented code blocks have been deleted (which is good) and some unused method have been deleted (which is super good). I asked only to have a general idea of your work, I need no justification ;) Thanks again for you work! +1

**Review by marcosgopen — APPROVED** [review]
Approved! +1

**Comment by mmusgrov** [comment]
@marcosgopen I updated the PR description since the change set also addresses JBTM-3413

**Pull request merged**
