### PR TITLE
[JBTM-3637] Remove references to Log4j 1

### PR DESCRIPTION
**Pull request by marcosgopen**
https://issues.redhat.com/browse/JBTM-3637
Remove log4j ( https://mvnrepository.com/artifact/log4j/log4j)  from ./ArjunaJTA/jms/pom.xml ./ArjunaJTS/jts/pom.xml ./qa/pom.xml ./rts/at/util/pom.xml

CORE TOMCAT AS_TESTS RTS !JACOCO XTS QA_JTA QA_JTS_OPENJDKORB !PERF LRA !DB_TESTS !mysql !db2 !postgres !oracle

### CODE REVIEW

**Comment by marcosgopen** [comment]
@mmusgrov I have just seen AS_TESTS profile tests failed. I don't think those tests are related to this PR, are they?

**Comment by mmusgrov** [comment]
@marcosgopen This PR contains the `Hold` label, do you need me to review it?

**Comment by marcosgopen** [comment]
@mmusgrov yes please. I have removed the Hold flag now. Thanks

**Review by mmusgrov — APPROVED** [review]
I agree that the failures on the AS-TESTS axis is unrelated so I think this one can be merged.

**Pull request merged**
