### PR TITLE
[JBTM-3759] Missing version in the bom for dependency log4j-core

### PR DESCRIPTION
**Pull request by moulalis**
Issue: https://issues.redhat.com/browse/JBTM-3759

JDK17 QA_JTA QA_JTS_OPENJDKORB JACOCO

### CODE REVIEW

**Comment by jmfinelli** [comment]
Could you please add all needed testing axis in the description of this PR? Thanks :-)

**Comment by marcosgopen** [comment]
You can find all the axis at https://github.com/jbosstm/narayana/blob/main/PULL_REQUEST_TEMPLATE.md 
The axis are "CORE TOMCAT AS_TESTS RTS JACOCO XTS QA_JTA QA_JTS_OPENJDKORB PERF LRA DB_TESTS mysql db2 postgres oracle" and in order to test them on CI you need to add them in the PR's description.

**Comment by mmusgrov** [comment]
FYI: the instructions for running CI on a PR are: https://github.com/jbosstm/narayana/blob/main/PULL_REQUEST_TEMPLATE.md

I assume that not specifying any axis means that it won't be tested by CI.

**Review by marcosgopen — APPROVED** [review]
Thank you @moulalis for your PR. It looks good! The PERFORMANCE and AS_TESTS errors are not related to this PR, therefore I approve it!

**Pull request merged**
