### PR TITLE
JBTM-2949 - Replace WeakHashMap with a thread-safe alternative in ThreadUtil

### PR DESCRIPTION
**Pull request by barreiro**
https://issues.jboss.org/browse/JBTM-2949

!RTS !XTS !BLACKTIE !QA_JTS_JDKORB !QA_JTS_JACORB !QA_JTS_OPENJDKORB !MAIN !AS_TESTS NO_WIN !QA_JTA

Alternative to #1235 using strategy 1, a ConcurrentWeakHashMap implemented using a ConcurrentHashMap with WeakReferences as keys.

### CODE REVIEW

**Comment by mmusgrov** [comment]
@barreiro This looks like an interesting solution too.

We have not seen any perf or contention issues in this area of the code before particularly since most applications do not share a transaction between multiple threads. You reported that synchronizing on the weak hash map does not scale well enough under high contention. Would it be possible for you to outline the tools you have been using and the application you are testing with (is it one of the spec benchmarks and if so which test).

**Comment by barreiro** [comment]
@mmusgrov It doesn't matter if a transaction spans across multiple threads or not. The method being synchronized means that only one ID can be fetched at any given point in time. Running SPEC jEnterprise 2010 with hundreds of threads and it shows that the amount of time threads spend waiting to get an ID is significant (I can quantify if needed). I assume that you don't see this as a contention spot in your benchmarks because you don't get to this scale.

BTW I don't see results from the perf CI job on this pull request. Can someone restart the job?

**Comment by mmusgrov** [comment]
@barreiro I mean if a transaction does not spawn child actions (I would be surprised if the spec benchmark does that) then it should not be even calling the synchronized method and therefore this performance enhancement should not come into play. Can you post one of the call stacks that show it hitting this method please.

I have restarted the PERF job.

**Comment by barreiro** [comment]
@mmusgrov here are the top 3 call stacks: 
```
com.arjuna.ats.arjuna.utils.ThreadUtil.getThreadId(Thread)
com.arjuna.ats.arjuna.coordinator.BasicAction.addChildThread(Thread)
com.arjuna.ats.internal.arjuna.thread.ThreadActionData.pushAction(BasicAction, boolean)
com.arjuna.ats.internal.arjuna.thread.ThreadActionData.pushAction(BasicAction)
com.arjuna.ats.arjuna.AtomicAction.begin(int)
com.arjuna.ats.internal.jta.transaction.arjunacore.TransactionImple.<init>(int)
com.arjuna.ats.internal.jta.transaction.arjunacore.BaseTransaction.begin()
com.arjuna.ats.jbossatx.BaseTransactionManagerDelegate.begin()
org.wildfly.transaction.client.provider.jboss.JBossLocalTransactionProvider.createNewTransaction(int)
org.wildfly.transaction.client.LocalTransactionContext.beginTransaction(int, boolean, CreationListener$CreatedBy)
org.wildfly.transaction.client.ContextTransactionManager.begin(CreationListener$CreatedBy)
org.wildfly.transaction.client.ContextTransactionManager.begin()
org.jboss.as.ejb3.tx.CMTTxInterceptor.beginTransaction(TransactionManager)
org.jboss.as.ejb3.tx.CMTTxInterceptor.invokeInOurTx(InterceptorContext, TransactionManager, EJBComponent)
org.jboss.as.ejb3.tx.CMTTxInterceptor.required(InterceptorContext, EJBComponent, int)
org.jboss.as.ejb3.tx.CMTTxInterceptor.processInvocation(InterceptorContext)
org.jboss.invocation.InterceptorContext.proceed()
org.jboss.as.ejb3.component.interceptors.CurrentInvocationContextInterceptor.processInvocation(InterceptorContext)
org.jboss.invocation.InterceptorContext.proceed()
org.jboss.as.ejb3.component.invocationmetrics.WaitTimeInterceptor.processInvocation(InterceptorContext)
org.jboss.invocation.InterceptorContext.proceed()
org.jboss.as.ejb3.security.IdentityOutflowInterceptor.processInvocation(InterceptorContext)
org.jboss.invocation.InterceptorContext.proceed()
org.jboss.as.ejb3.security.SecurityDomainInterceptor.processInvocation(InterceptorContext)
org.jboss.invocation.InterceptorContext.proceed()
org.jboss.as.ejb3.deployment.processors.StartupAwaitInterceptor.processInvocation(InterceptorContext)
org.jboss.invocation.InterceptorContext.proceed()
org.jboss.as.ejb3.component.interceptors.ShutDownInterceptorFactory$1.processInvocation(InterceptorContext)
org.jboss.invocation.InterceptorContext.proceed()
org.jboss.as.ejb3.component.interceptors.LoggingInterceptor.processInvocation(InterceptorContext)
org.jboss.invocation.InterceptorContext.proceed()
org.jboss.as.ee.component.NamespaceContextInterceptor.processInvocation(InterceptorContext)
org.jboss.invocation.InterceptorContext.proceed()
org.jboss.as.ejb3.component.interceptors.AdditionalSetupInterceptor.processInvocation(InterceptorContext)
org.jboss.invocation.InterceptorContext.proceed()
org.jboss.invocation.ContextClassLoaderInterceptor.processInvocation(InterceptorContext)
org.jboss.invocation.InterceptorContext.proceed()
org.jboss.invocation.InterceptorContext.run()
org.wildfly.security.manager.WildFlySecurityManager.doChecked(PrivilegedExceptionAction)
org.jboss.invocation.AccessCheckingInterceptor.processInvocation(InterceptorContext)
org.jboss.invocation.InterceptorContext.proceed()
org.jboss.invocation.ChainedInterceptor.processInvocation(InterceptorContext)
org.jboss.as.ee.component.ViewService$View.invoke(InterceptorContext)
org.jboss.as.ee.component.ViewDescription$1.processInvocation(InterceptorContext)
org.jboss.as.ee.component.ProxyInvocationHandler.invoke(Object, Method, Object[])
org.spec.jent.ejb.orders.session.CustomerSessionLocal$$$view25.sellInventory(Integer, long, boolean)
```
```
com.arjuna.ats.arjuna.utils.ThreadUtil.getThreadId(Thread)
com.arjuna.ats.arjuna.coordinator.BasicAction.addChildThread(Thread)
com.arjuna.ats.internal.arjuna.thread.ThreadActionData.pushAction(BasicAction, boolean)
com.arjuna.ats.internal.arjuna.thread.ThreadActionData.pushAction(BasicAction)
com.arjuna.ats.internal.arjuna.thread.ThreadActionData.restoreActions(BasicAction)
com.arjuna.ats.arjuna.AtomicAction.resume(AtomicAction)
com.arjuna.ats.internal.jta.transaction.arjunacore.TransactionManagerImple.resume(Transaction)
com.arjuna.ats.jbossatx.BaseTransactionManagerDelegate.resume(Transaction)
org.wildfly.transaction.client.LocalTransaction.resume()
org.wildfly.transaction.client.ContextTransactionManager.resume(AbstractTransaction)
org.wildfly.transaction.client.ContextTransactionManager.begin(CreationListener$CreatedBy)
org.wildfly.transaction.client.ContextTransactionManager.begin()
org.jboss.as.ejb3.tx.CMTTxInterceptor.beginTransaction(TransactionManager)
org.jboss.as.ejb3.tx.CMTTxInterceptor.invokeInOurTx(InterceptorContext, TransactionManager, EJBComponent)
org.jboss.as.ejb3.tx.CMTTxInterceptor.required(InterceptorContext, EJBComponent, int)
org.jboss.as.ejb3.tx.CMTTxInterceptor.processInvocation(InterceptorContext)
org.jboss.invocation.InterceptorContext.proceed()
org.jboss.as.ejb3.component.interceptors.CurrentInvocationContextInterceptor.processInvocation(InterceptorContext)
org.jboss.invocation.InterceptorContext.proceed()
org.jboss.as.ejb3.component.invocationmetrics.WaitTimeInterceptor.processInvocation(InterceptorContext)
org.jboss.invocation.InterceptorContext.proceed()
org.jboss.as.ejb3.security.IdentityOutflowInterceptor.processInvocation(InterceptorContext)
org.jboss.invocation.InterceptorContext.proceed()
org.jboss.as.ejb3.security.SecurityDomainInterceptor.processInvocation(InterceptorContext)
org.jboss.invocation.InterceptorContext.proceed()
org.jboss.as.ejb3.deployment.processors.StartupAwaitInterceptor.processInvocation(InterceptorContext)
org.jboss.invocation.InterceptorContext.proceed()
org.jboss.as.ejb3.component.interceptors.ShutDownInterceptorFactory$1.processInvocation(InterceptorContext)
org.jboss.invocation.InterceptorContext.proceed()
org.jboss.as.ejb3.component.interceptors.LoggingInterceptor.processInvocation(InterceptorContext)
org.jboss.invocation.InterceptorContext.proceed()
org.jboss.as.ee.component.NamespaceContextInterceptor.processInvocation(InterceptorContext)
org.jboss.invocation.InterceptorContext.proceed()
org.jboss.as.ejb3.component.interceptors.AdditionalSetupInterceptor.processInvocation(InterceptorContext)
org.jboss.invocation.InterceptorContext.proceed()
org.jboss.invocation.ContextClassLoaderInterceptor.processInvocation(InterceptorContext)
org.jboss.invocation.InterceptorContext.proceed()
org.jboss.invocation.InterceptorContext.run()
org.wildfly.security.manager.WildFlySecurityManager.doChecked(PrivilegedExceptionAction)
org.jboss.invocation.AccessCheckingInterceptor.processInvocation(InterceptorContext)
org.jboss.invocation.InterceptorContext.proceed()
org.jboss.invocation.ChainedInterceptor.processInvocation(InterceptorContext)
org.jboss.as.ee.component.ViewService$View.invoke(InterceptorContext)
org.jboss.as.ee.component.ViewDescription$1.processInvocation(InterceptorContext)
org.jboss.as.ee.component.ProxyInvocationHandler.invoke(Object, Method, Object[])
org.spec.jent.ejb.orders.session.CustomerSessionLocal$$$view25.sellInventory(Integer, long, boolean)
```
```
com.arjuna.ats.arjuna.utils.ThreadUtil.getThreadId(Thread)
com.arjuna.ats.arjuna.utils.ThreadUtil.getThreadId()
com.arjuna.ats.internal.arjuna.thread.ThreadActionData.popAction()
com.arjuna.ats.arjuna.AtomicAction.commit(boolean)
com.arjuna.ats.internal.jta.transaction.arjunacore.TransactionImple.commitAndDisassociate()
com.arjuna.ats.internal.jta.transaction.arjunacore.BaseTransaction.commit()
com.arjuna.ats.jbossatx.BaseTransactionManagerDelegate.commit()
org.wildfly.transaction.client.LocalTransaction.commitAndDissociate()
org.wildfly.transaction.client.ContextTransactionManager.commit()
org.jboss.as.ejb3.tx.CMTTxInterceptor.endTransaction(TransactionManager, Transaction)
org.jboss.as.ejb3.tx.CMTTxInterceptor.invokeInOurTx(InterceptorContext, TransactionManager, EJBComponent)
org.jboss.as.ejb3.tx.CMTTxInterceptor.required(InterceptorContext, EJBComponent, int)
org.jboss.as.ejb3.tx.CMTTxInterceptor.processInvocation(InterceptorContext)
org.jboss.invocation.InterceptorContext.proceed()
org.jboss.as.ejb3.component.interceptors.CurrentInvocationContextInterceptor.processInvocation(InterceptorContext)
org.jboss.invocation.InterceptorContext.proceed()
org.jboss.as.ejb3.component.invocationmetrics.WaitTimeInterceptor.processInvocation(InterceptorContext)
org.jboss.invocation.InterceptorContext.proceed()
org.jboss.as.ejb3.security.IdentityOutflowInterceptor.processInvocation(InterceptorContext)
org.jboss.invocation.InterceptorContext.proceed()
org.jboss.as.ejb3.security.SecurityDomainInterceptor.processInvocation(InterceptorContext)
org.jboss.invocation.InterceptorContext.proceed()
org.jboss.as.ejb3.deployment.processors.StartupAwaitInterceptor.processInvocation(InterceptorContext)
org.jboss.invocation.InterceptorContext.proceed()
org.jboss.as.ejb3.component.interceptors.ShutDownInterceptorFactory$1.processInvocation(InterceptorContext)
org.jboss.invocation.InterceptorContext.proceed()
org.jboss.as.ejb3.component.interceptors.LoggingInterceptor.processInvocation(InterceptorContext)
org.jboss.invocation.InterceptorContext.proceed()
org.jboss.as.ee.component.NamespaceContextInterceptor.processInvocation(InterceptorContext)
org.jboss.invocation.InterceptorContext.proceed()
org.jboss.as.ejb3.component.interceptors.AdditionalSetupInterceptor.processInvocation(InterceptorContext)
org.jboss.invocation.InterceptorContext.proceed()
org.jboss.invocation.ContextClassLoaderInterceptor.processInvocation(InterceptorContext)
org.jboss.invocation.InterceptorContext.proceed()
org.jboss.invocation.InterceptorContext.run()
org.wildfly.security.manager.WildFlySecurityManager.doChecked(PrivilegedExceptionAction)
org.jboss.invocation.AccessCheckingInterceptor.processInvocation(InterceptorContext)
org.jboss.invocation.InterceptorContext.proceed()
org.jboss.invocation.ChainedInterceptor.processInvocation(InterceptorContext)
org.jboss.as.ee.component.ViewService$View.invoke(InterceptorContext)
org.jboss.as.ee.component.ViewDescription$1.processInvocation(InterceptorContext)
org.jboss.as.ee.component.ProxyInvocationHandler.invoke(Object, Method, Object[])
org.spec.jent.ejb.orders.session.CustomerSessionLocal$$$view25.sellInventory(Integer, long, boolean)
```

**Comment by mmusgrov** [comment]
@tomjenkinson manana

**Comment by mmusgrov** [comment]
Triggered a rebuild to compare against JBTM-2990

**Pull request closed without merging**
