### PR TITLE
[JBTM-3109][lra#94] renaming LRA status complete/compensate to close/cancel

### PR DESCRIPTION
**Pull request by ochaloup**
https://issues.jboss.org/browse/JBTM-3109

Based on the changes in LRA TCK the LRA status methods were renamed to
close and cancel.

https://github.com/eclipse/microprofile-lra/issues/94
https://github.com/eclipse/microprofile-lra/pull/98

!QA_JTA !QA_JTS_JDKORB !QA_JTS_OPENJDKORB !QA_JTS_JACORB !BLACKTIE !XTS !PERF NO_WIN !RTS !AS_TESTS !TOMCAT !JACOCO

### CODE REVIEW

**Comment by ochaloup** [comment]
@mmusgrov I'm on PTO next week, if there are needed some changes of this PR, please feel free to close this one and open new one with adjustments for you being able to merge it.

**Comment by ochaloup** [comment]
@xstefank as we talked there is some strange way how the shrinkwrap evaluates dependencies and way how the maven brings the dependencies in. There happens to be the dependency version clash. As the `org.eclipse.microprofile.lra:microprofile-lra-tck` defines dependency to `org.eclipse.microprofile.lra:microprofile-lra-api:${project.version}` (https://github.com/eclipse/microprofile-lra/blob/master/tck/pom.xml#L59) and the project version is `1.0-SNAPSHOT` then the latest LRA snapshot is taken and causes the clash. It seems the shrinkwrap and for example `maven source plugin` takes this latest version based on the definition from the tck. What I did was to change the scope from `test` to `provided` and in that way the dependency was resolved correctly. Unfortunately I don't understand in details why it is so.

The second failure was the 

```
java.lang.RuntimeException: java.lang.ClassNotFoundException: org.glassfish.jersey.client.JerseyClientBuilder
        at org.eclipse.microprofile.lra.tck.TckCancelOnTests.beforeClass(TckCancelOnTests.java:76)
Caused by: java.lang.ClassNotFoundException: org.glassfish.jersey.client.JerseyClientBuilder
        at org.eclipse.microprofile.lra.tck.TckCancelOnTests.beforeClass(TckCancelOnTests.java:76)
```

I thought I already fixed this issue by using `META-INF/services/javax.ws.rs.client.ClientBuilder` descriptor in the auxiliary file. But for some reason this does not fix the issue. For that reason I followed the advices https://developer.jboss.org/thread/241325 and defined dependency on the resteasy client to the pom.xml. That way it works for me.

**Comment by ochaloup** [comment]
I'm going to merge this while it fixes the issue with the changes in interface lra#94 and should fix the trouble with the dependency failures. If there is some more troubles with dependencies I will address it in the next PR.

**Comment by mmusgrov** [comment]
Please ignore the MAIN and BLACKTIE profile tests. I was setting up a PR poller job on our Jenkins installation. I temporarily added a build periodically schedule and it started retesting all the PRs. Since the job config was incorrect it rapidly cycled through old PRs before I was able to stop it. Sorry about that. It is disabled now.

**Pull request merged**
