### PR TITLE
[JBTM-2213] Minimize deprecation warnings in txframework

### PR DESCRIPTION
**Pull request by Gytis**
!PERF !BLACKTIE !MAIN !QA_JTA !QA_JTS_JACORB

### CODE REVIEW

**Comment by mmusgrov** [comment]
I like your fix but how will our users figure out what is and what isn't deprecated.

**Comment by Gytis** [comment]
This should only minimize warnings when building Narayana. It shouldn't influence user software builds. Also, it doesn't completely remove warnings, but minimizes from ~50-100 lines to 3-5 lines.

**Comment by mmusgrov** [comment]
Yes

**Comment by Gytis** [comment]
merged

**Pull request closed without merging**
