### PR TITLE
JBTM-3532 Add LRA support for EE 9

### PR DESCRIPTION
**Pull request by xstefank**
https://issues.redhat.com/browse/JBTM-3532

!CORE !TOMCAT !AS_TESTS !RTS !JACOCO !XTS !QA_JTA !QA_JTS_JACORB !QA_JTS_JDKORB !QA_JTS_OPENJDKORB !PERF LRA !DB_TESTS !mysql !db2 !postgres !oracle

Don't merge. This contains a change in the script to download WFLY Preview instead of default WFLY.

### CODE REVIEW

**Comment by xstefank** [comment]
don't know what is wrong with GH actions. Same branch, same master, same GH action passed in my fork - https://github.com/xstefank/narayana/pull/13. Does anyone know why CI isn't starting the LRA job?

**Comment by mmusgrov** [comment]
@mayankkunwar will you take a look at this one please

**Comment by mayankkunwar** [comment]
Okay @mmusgrov I will review it

**Comment by xstefank** [comment]
@mayankkunwar can you please try to restart GH actions?

**Comment by mayankkunwar** [comment]
I have restarted GH actions

**Comment by mmusgrov** [comment]
@mayankkunwar we are still getting failures on this PR.
The last one looks like testCompensateFailed(io.narayana.lra.arquillian.FailedLRAIT), I've seen that before so we need a JIRA for it if we don't already have one.
Will you check the failures and verify that they are unrelated to Martin's changes.

**Comment by mayankkunwar** [comment]
The last run in the CI for JDK8 was successful and I also saw this issue earlier, I think it already exist, though I will go through the PR changes once more.
I will check if there is already any JIRA related to this issue, if not, then I will create one for the same.

**Comment by mayankkunwar** [comment]
I have verified that the failures that happened on the last `LRA JDK8` build is not related to this PR. The issue already exist

**Comment by mmusgrov** [comment]
@xstefank thanks for this contribution

**Pull request merged**
