### PR TITLE
JBTM-2695 Service service jboss.ejb.default-resource-adapter-name-service not found

### PR DESCRIPTION
**Pull request by zhfeng**
https://issues.jboss.org/browse/JBTM-2695

!XTS !PERF !QA_JTA !QA_JTS_JACORB !QA_JTS_JDKORB !QA_JTS_OPENJDKORB

### CODE REVIEW

**Comment by mmusgrov** [comment]
Urgent: @zhfeng Amos is this ready to merge yet?

**Comment by zhfeng** [comment]
@mmusgrov it should be OK but the http://albany.eng.hst.ams2.redhat.com/job/btny-pulls-narayana-jdk8/1541/PROFILE=BLACKTIE,jdk=jdk8.latest,label=linux64el5/console shows that the AdvertiseUnadvertiseTest is hanging. I will take a look at the server.log ASAP.

**Comment by zhfeng** [comment]
re-test on the linux

**Comment by zhfeng** [comment]
It is still hanging with the blacktie-admin-services tests sometimes.

**Comment by zhfeng** [comment]
It looks good now and I will create another jira for the hanging issue.

**Comment by mmusgrov** [comment]
I pushed you commits to master and have kicked off another build.

**Pull request closed without merging**
