### PR TITLE
JBTM-3015 Fix the TestExecutor to close the connection at the end of test

### PR DESCRIPTION
**Pull request by zhfeng**
!RTS !QA_JTS_OPENJDKORB !AS_TESTS !QA_JTA !QA_JTS_JACORB !BLACKTIE !QA_JTS_JDKORB !XTS NO_WIN !MAIN !PERF

### CODE REVIEW

**Comment by zhfeng** [comment]
It is still failing with the H2 in the CI building and I'm looking into the failures.

**Comment by Karm** [comment]
I tested locally with PostgreSQL from Docker:
    
    mvn clean install integration-test -Dtest.db.type=container -P arq-tomcat

Lemme check with H2 too...

**Comment by Karm** [comment]
H2 fails locally on:
```
java.sql.SQLException: Unable to enlist connection in transaction: enlistResource returns &#39;false&#39;.
	org.apache.tomcat.dbcp.dbcp2.managed.TransactionContext.setSharedConnection(TransactionContext.java:95)
	org.apache.tomcat.dbcp.dbcp2.managed.ManagedConnection.updateTransactionStatus(ManagedConnection.java:141)
	org.apache.tomcat.dbcp.dbcp2.managed.ManagedConnection.&lt;init&gt;(ManagedConnection.java:59)
	org.apache.tomcat.dbcp.dbcp2.managed.ManagedDataSource.getConnection(ManagedDataSource.java:81)
	org.jboss.narayana.tomcat.jta.integration.app.TestExecutor.verifyRecovery(TestExecutor.java:107)
```

**Comment by Karm** [comment]
@zhfeng Does it make sense to feed some more conf options to H2 here? Like # of connections...? Not sure. I though it being not pertinent for in memory h2 in such a case...

See: https://github.com/jbosstm/narayana/blob/master/tools/src/main/java/io/narayana/db/H2Allocator.java#L44

**Comment by zhfeng** [comment]
@tomjenkinson it means that we need to force close the H2 connection when returning to the pool ?

**Comment by zhfeng** [comment]
yeah, I've squash your commit.

**Comment by Karm** [comment]
(passes both H2 and PostgreSQL for me :+1: )

**Pull request merged**
