### PR TITLE
BUILD SCRIPT ONLY: Allow the controlling of the nexus plugin separate…

### PR DESCRIPTION
**Pull request by tomjenkinson**
CORE !AS_TESTS !RTS !JACOCO !XTS !QA_JTA !QA_JTS_OPENJDKORB !PERFORMANCE !LRA !DB_TESTS mysql db2 postgres oracle
!JDK17

### CODE REVIEW

**Review by mmusgrov — APPROVED** [review]
Looks good.

So we can now test a release without necessarily deploying to nexus?

**Comment by mmusgrov** [comment]
Thanks, I assume that you had a use case in mind!

**Comment by marcosgopen** [comment]
> With this we can control the deployment to nexus separately so by default a `./build.sh deploy [...]` will not deploy to Nexus. To deploy to nexus we just do `./build.sh deploy -DskipNexusStagingDeployMojo=false [...]`

@tomjenkinson I assume you mean `./build.sh deploy  -DskipMavenDeployMojo=true`

**Comment by marcosgopen** [comment]
> I don't think there is a `skipNexusDeployMojo`? I am going to guess you are referring to `skipMavenDeployMojo`?
> 
> `skipMavenDeployMojo` controls the `maven-deploy-plugin` and `skipNexusStagingDeployMojo` controls the `nexus-staging-maven-plugin`

Thanks Tom, yes I was referring to skipMavenDeployMojo. Ok, I see.

**Comment by mmusgrov** [comment]
> With this we can control the deployment to nexus separately so by default a `./build.sh deploy [...]` will not deploy to Nexus. To deploy to nexus we just do `./build.sh deploy -DskipNexusStagingDeployMojo=false [...]`

Yes the property behaviour is clear, but when would we not want to deploy to nexus, don't we need to do that first in order to have the artifacts synced to maven central.

**Comment by mmusgrov** [comment]
> We do want to be able to release to Nexus, but it's not guaranteed we want to do that every time we do mvn deploy (e.g to deploy to a local file system). This change allows for that flexibility.

Why did you need to deploy to your local filesystem, were you testing the veracity of the release scripts, or was it for other reasons?

**Pull request merged**
