### PR TITLE
[JBTM-3361] double-check locking idiom fix

### PR DESCRIPTION
**Pull request by ochaloup**
https://issues.redhat.com/browse/JBTM-3361

!QA_JTA !QA_JTS_JDKORB !QA_JTS_OPENJDKORB !QA_JTS_JACORB !BLACKTIE !XTS !PERF NO_WIN !RTS !AS_TESTS !TOMCAT !JACOCO !LRA

### CODE REVIEW

**Review by mmusgrov — APPROVED** [review]
Did you manage to produce a failure where this test misbehaved?

If we are going to fix issues by code inspection without accompanying test cases/reproducers then the source base will eventually destabilise.

**Comment by ochaloup** [comment]
@mmusgrov I don't understand the point about destabilization.
I was not planning to write a test as this is a way how the java works. Writing a test for this means to write a test of java memory model.

This PR is approved but with the comment above I'm now not sure if it's ok to be merged in this form. @mmusgrov may I mege it?

**Comment by mmusgrov** [comment]
Approving a PR means it is approved and okay to merge. But such comments should still elicit a response even though they don't block the merge.

My point was that if an engineer goes through a code base looking for things that look dodgy and changes them without a test then that is going to introduce potential bugs - that is what I meant by destabilise the code base.

**Comment by ochaloup** [comment]
I regurarly go through the Coverity report run by QE team. More info here https://source.redhat.com/groups/public/jboss-enterprise-application-platform-qe/jboss_enterprise_application_platform_qe_wiki/brq_coverity_instance

**Pull request merged**
