### PR TITLE
JBTM-3501: Move BlackTie code to a separate repository

### PR DESCRIPTION
**Pull request by mayankkunwar**
https://issues.redhat.com/browse/JBTM-3501

The PR consists of following changes:
1. Removed Blacktie release scripts
2. Removed Blacktie CI build scripts
3. Removed Blacktie source code

MAIN CORE !TOMCAT AS_TESTS !RTS !JACOCO !XTS !QA_JTA !QA_JTS_JACORB !QA_JTS_JDKORB !QA_JTS_OPENJDKORB !BLACKTIE !PERF !LRA !NO_WIN !DB_TESTS !mysql !db2 !postgres !oracle

### CODE REVIEW

**Comment by mmusgrov** [comment]
Can we move the BlackTie code to its new repo such that the git commit history is maintained.

**Comment by mayankkunwar** [comment]
> Can we move the BlackTie code to its new repo such that the git commit history is maintained.

I was working on it in separate repo.

**Comment by mmusgrov** [comment]
The quickstart repo depends on blacktie so you will need to do that one first.

**Comment by mayankkunwar** [comment]
Okay

**Comment by mmusgrov** [comment]
> The quickstart repo depends on blacktie so you will need to do that one first.
> You should be able to migrate that to the same repo (just create a new top level directory for them).

I will put this PR on HOLD until BlackTie is removed from the quickstart repo.

**Review by mmusgrov — APPROVED** [review]

**Comment by mayankkunwar** [comment]
`narayana.bat` was just trying to run BlackTie on windows system, so if we wouldn't have removed it, it would have failed, since in this repo, we are removing BlackTie source code.

**Comment by mmusgrov** [comment]
I'm not sure how I missed that one ;-)

**Pull request merged**
