### PR TITLE
JBTM-2414 Upgrade JBoss Logging Version

### PR DESCRIPTION
**Pull request by zhfeng**
!PERF !QA_JTS_JACORB !QA_JTA

### CODE REVIEW

**Comment by zhfeng** [comment]
Thanks Tom, I will take a look at this failure.

**Comment by zhfeng** [comment]
The MAIN builds failed with OSGI Test that dues to the arquillian-container-karaf-embedded 2.1.0.CR15 only works with arquillian-core 1.1.2.Final

**Comment by mmusgrov** [comment]
Why not simply not upgrade arquilian. For example see https://github.com/jbosstm/narayana/pull/852

**Comment by zhfeng** [comment]
It looks like all of them are complied against with arquillian-core 1.1.2.Final see
http://arquillian.org/modules/arquillian-osgi-karaf-embedded-container-adapter/
So I agree with Mike to not upgrade the arquillian-core

**Comment by mmusgrov** [comment]
I disabled the QA_JTS_JACORB and QA_JTA profiles for this PR since we don't use the app server in the qa test suite.

**Comment by mmusgrov** [comment]
Amos, I am going to kill the running PERF axis for this job since it does need it.

**Comment by zhfeng** [comment]
The MAIN build failed with
```
testCrashBeforeCommit(org.jboss.narayana.rest.integration.test.integration.RecoveryIntegrationTestCase)  Time elapsed: 113.931 sec  <<< FAILURE!
java.lang.AssertionError: Recovery failed
	at org.junit.Assert.fail(Assert.java:88)
	at org.jboss.narayana.rest.integration.test.integration.RecoveryIntegrationTestCase.testCrashBeforeCommit(RecoveryIntegrationTestCase.java:125)
```
and the BLACKTIE build on Windows failed I think it's related to JBTM-2420.

**Comment by mmusgrov** [comment]
Also note that master has now moved on to 10.0.0.Alpha3-SNAPSHOT.

**Comment by zhfeng** [comment]
@tomjenkinson - rebase the branch

**Comment by zhfeng** [comment]
It looks good to me !

**Pull request closed without merging**
