### PR TITLE
JBTM-2846 Make actionStatus volatile

### PR DESCRIPTION
**Pull request by mmusgrov**
https://issues.jboss.org/browse/JBTM-2846

!BLACKTIE !XTS !QA_JTA !QA_JTS_JACORB !QA_JTS_JDKORB

### CODE REVIEW

**Comment by mmusgrov** [comment]
I did not include a test case since it is clear by reading the code that there is at least one path where reordering of writes to actionStatus can result in seeing the wrong status (as your test case would in fact prove).

**Comment by mmusgrov** [comment]
@tomjenkinson the PERF profile did not run so that needs looking into (missing benchmark.jar). I cannot tell how long it has been broken for since for every PR I looked at (at least the last 10) people are setting !PERF lol (are they telling me/us something).

**Comment by mmusgrov** [comment]
I updated the PR indicating why I think this fix is sufficient. If we foresee any other issues we can raise a separate JIRA for it.

**Comment by dmlloyd** [comment]
@tomjenkinson Sorry, my Internet was out this morning after a storm.

Yes, the change is equivalent in terms of functionality, it just removes the race conditions by making read-and-assign be atomic as well as using volatile to prevent stale read situations.

**Pull request merged**
