### PR TITLE
[JBTM-3395] fixes of failures on the basic IT tests

### PR DESCRIPTION
**Pull request by ochaloup**
https://issues.redhat.com/browse/JBTM-3395

!MAIN !CORE !QA_JTA !QA_JTS_JDKORB !QA_JTS_OPENJDKORB !QA_JTS_JACORB !BLACKTIE !XTS !PERF NO_WIN !RTS !AS_TESTS !TOMCAT !JACOCO
LRA

### CODE REVIEW

**Review by mmusgrov — COMMENTED** [review]
Damn, I've just finished fixing this because it was causing one of my fixes to fail.

You need to be checking for NOT_FOUND. Also the TCK already tests it so it doesn't belong here. If fixed it as follows:

```java
    // test that an active LRA is reported correctly and then test that a closed LRA is reported correctly
    // Note that the TCK already has tests that start and close LRAs so this so this one needs removing
    @Test
    public void testGetAllLRAs() {
        URI lra = lraClient.startLRA("test-lra");

        List<LRAData> allLRAs = lraClient.getAllLRAs();
        Assert.assertTrue(allLRAs.stream().anyMatch(lraData -> lraData.getLraId().equals(lra.toASCIIString())));

        lraClient.closeLRA(lra);

        try {
            Assert.assertNotEquals(LRAStatus.Active, lraClient.getStatus(lra));
        } catch (WebApplicationException e) {
            assertEquals("LRA should have finished",
                    Response.Status.NOT_FOUND.getStatusCode(),
                    e.getResponse().getStatus());
        }
    }
```

**Comment by mmusgrov** [comment]
The fix I'm working on has about 4 commits in it and this fix is 2 commits back. If you can change your PR to remove the test then that will make it easier for me to fix up my own fix (or I can do it in mine).

**Comment by ochaloup** [comment]
@mmusgrov 
Do you mean the fix for this issue will be part of the https://github.com/jbosstm/narayana/pull/1729 or some another upcoming PR?

I can close this PR if you have got a fix for this.
And the check `Assert.assertNotEquals(LRAStatus.Active, lraClient.getStatus(lra));` sounds better than mine.
Just, do you plan to proceed with with that multi commit PR soon? Or would be possible to rip off just the fix for this and make a separate PR now?

**Comment by mmusgrov** [comment]
Well I had already fixed it because it was blocking my multi commit PR #1729 and it has been merged with that PR. But I also suggested that we [already have tests](https://github.com/eclipse/microprofile-lra/blob/master/tck/src/main/java/org/eclipse/microprofile/lra/tck/TckTests.java#L93) (and the one in the same file on line #L114) for this functionality so I was really suggesting that we simply delete the test.

**Comment by xstefank** [comment]
The idea of that test is to test `lraClient.getAllLRAs()` not start/stop.

**Comment by ochaloup** [comment]
@mmusgrov ok, I see, I didn't got that. I'm closing the PR and the issue.

About the deleting the test I agree with @xstefank as the test checks the functionality of the `LRAClient` method and it should not be deleted. In contrary more tests should be added as we lack the test coverage of the `LRAClient`.

**Comment by mmusgrov** [comment]
I reopened it.

**Review by mmusgrov — APPROVED** [review]

**Pull request merged**
