### PR TITLE
JBTM-3140 Update LRA to 1.0-20190429.061212-359

### PR DESCRIPTION
**Pull request by xstefank**
https://issues.jboss.org/browse/JBTM-3140

NestedLRA annotation was removed from the specification.

!QA_JTA !QA_JTS_JDKORB !QA_JTS_OPENJDKORB !QA_JTS_JACORB !BLACKTIE !XTS !PERF NO_WIN !AS_TESTS !TOMCAT !JACOCO !mysql !postgres !db2 !oracle !RTS

### CODE REVIEW

**Comment by xstefank** [comment]
I needed this for my work on the spec. @mmusgrov what does that mean? Should I add parent header handling or close this and let you rework it?

**Comment by mmusgrov** [comment]
No, I mean I am working on the Narayana fix for this.

**Comment by mmusgrov** [comment]
Give me until later on this afternoon and I will raise my PR

**Comment by xstefank** [comment]
so if I understood you correctly I should close this one. I can always reopen it if I misunderstood.

**Comment by mmusgrov** [comment]
Yes please

**Pull request closed without merging**
