### PR TITLE
[JBTM-2206] Use synchronized HashMaps

### PR DESCRIPTION
**Pull request by mmusgrov**
https://issues.jboss.org/browse/JBTM-2206
Resurrection of PR 679 originally raised by @jesperpedersen

PERF !RTS !XTS !BLACKTIE !QA_JTS_JDKORB !QA_JTS_JACORB !QA_JTS_OPENJDKORB !AS_TESTS NO_WIN !QA_JTA !MAIN

### CODE REVIEW

**Comment by nmcl** [comment]
Can we stop doing work on closed/rejected JIRAS please :) ?

**Comment by nmcl** [comment]
Should the title be changed since it doesn't match the title on the actual JIRA either?

**Comment by mmusgrov** [comment]
I updated the PR description and title to reflect the correct JIRA: https://issues.jboss.org/browse/JBTM-2206

**Comment by mmusgrov** [comment]
@tomjenkinson the store tests on the Amsterdam cluster completed fine with a 500% improvement.

We will need to wait until I am in the Newcastle office (on Friday) to figure out why that axis didn't finish correctly (maybe the power failed again but let's wait until Friday).

**Comment by mmusgrov** [comment]
@tomjenkinson So it was due to out of disk space on haverstraw.

**Pull request closed without merging**
