### PR TITLE
JBTM-3437 JMS 2.0 integration

### PR DESCRIPTION
**Pull request by tomjenkinson**
https://issues.redhat.com/browse/JBTM-3437

CORE !TOMCAT !AS_TESTS !RTS !JACOCO !XTS !QA_JTA !QA_JTS_JACORB !QA_JTS_JDKORB !QA_JTS_OPENJDKORB !BLACKTIE !PERF !LRA !NO_WIN !DB_TESTS !mysql !db2 !postgres !oracle

(some commits on top of https://github.com/jbosstm/narayana/pull/1793)

### CODE REVIEW

**Comment by mmusgrov** [comment]
@tomjenkinson , thanks for moving this one along - I will take a look on Monday. Amos reviewed the other PR for this so perhaps @zhfeng could take a look at this one too.

**Review by zhfeng — APPROVED** [review]
Thanks @tomjenkinson and it looks good to me!

**Comment by mmusgrov** [comment]
This one has approval from one of the main stakeholders so I'm going to merge it.

**Comment by zhfeng** [comment]
Thanks @mmusgrov ! and is there any plan to do a new release of narayana?

**Comment by mmusgrov** [comment]
and #1966 as well

**Pull request merged**
