### PR TITLE
[JBTM-2961] changing the lra cdi rest testing to run swarm as process

### PR DESCRIPTION
**Pull request by ochaloup**
and not as in-vm embedded instance

https://issues.jboss.org/browse/JBTM-2961

There is a trouble with running cdi checker tests on Mac and as the embedded Swarm gets stuck time to time. This fix changes the test behaviour to start swarm as new java process for each deployment check.

!QA_JTA !QA_JTS_JDKORB !QA_JTS_OPENJDKORB !QA_JTS_JACORB !BLACKTIE !XTS !PERF NO_WIN !AS_TESTS !mysql !postgres !db2 !oracle

### CODE REVIEW

**Comment by ochaloup** [comment]
hi @mmusgrov , do you think you can check this change on the mac ci machines? I reworked the lra cdi tests to run in standalone process instead embedded in jvm which I think causes the issue.

**Comment by ochaloup** [comment]
@mmusgrov just for me to understand. Would be possible to check if this solves the issue on Mac CI? I mean I hope it could solve, it works locally and here passes, but if this still makes trouble for the Mac there will be needed to rethink approach.

The zt tooling is used only in tests. It's used for tooling. It's not used in the artifact released. Would be that still an issue? 

The reason for using zt is that the Java SE tools are not capable to provide many functionality which the library provides and they are harder to use. You need to create some wrapper for pumping outputs/inputs of commands, you are not able to find Pid of the process, if you want to you have to make that handling specific for each platform, you have the same issue with the stopping processes as that has to be written specifically. It's quite a lot of work that needs to be done, in general you need to make a small library for that. I can see many benefits to reuse this which already works and has fine api. Again, it's only tooling for tests it does not go to the release.

**Comment by mmusgrov** [comment]
I am having trouble getting the mac CI test machine to boot .. will let you know if I can breathe any life into it.

**Comment by mmusgrov** [comment]
@ochaloup After a disk repair I took your pr and ran it manually on soatest:

```
Tests run: 11, Failures: 0, Errors: 0, Skipped: 0

[INFO] 
[INFO] --- maven-failsafe-plugin:2.19.1:verify (default) @ lra-cdi-rest ---
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO] 
[INFO] lra-cdi-rest-parent ................................ SUCCESS [  4.090 s]
[INFO] CDI REST swarm template ............................ SUCCESS [ 12.671 s]
[INFO] LRA Cdi REST integration ........................... SUCCESS [02:42 min]
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 03:01 min
[INFO] Finished at: 2017-11-24T15:04:15+00:00
[INFO] Final Memory: 66M/675M
[INFO] ------------------------------------------------------------------------
```

**Comment by ochaloup** [comment]
@mmusgrov the tests pass, I will merge this

**Comment by ochaloup** [comment]
Closing this PR after talk with Mike as this is not a good way to provide checking of the lra. Let's create a standalone tool or maven plugin rather.

**Pull request closed without merging**
