### PR TITLE
[JBTM-3357] Do not cache CMR configuration properties

### PR DESCRIPTION
**Pull request by gaol**
Issue: https://issues.redhat.com/browse/JBTM-3357

MAIN AS_TESTS
!QA_JTA !QA_JTS_JDKORB !QA_JTS_OPENJDKORB !QA_JTS_JACORB !BLACKTIE !XTS !PERF NO_WIN !RTS !TOMCAT !JACOCO !LRA

Thanks for submitting your Pull Request!

Please make sure your PR meets the following requirements:
- [ ] Pull Request title is properly formatted: JBTM-XYZ Subject
- [ ] Pull Request contains link to the JIRA issue(s)

Our style rules for submitting code are as follows:

* If you add a new file it MUST adhere to our checkstyle ruleset.
  1. If you change a file (in a non trivial way) you are allowed (MAY) to reformat the code to conform to our checkstyle ruleset (`org.wildfly.checkstyle:wildfly-checkstyle-config`).
  2. If you choose not to reformat it then you SHOULD, where possible, try to follow the same style that's already in use for that file.

The build axis can be controlled by prefixing a ! on the following as appropriate.

MAIN TOMCAT AS_TESTS RTS JACOCO XTS QA_JTA QA_JTS_JACORB QA_JTS_JDKORB QA_JTS_OPENJDKORB BLACKTIE PERF LRA !NO_WIN DB_TESTS mysql db2 postgres oracle

### CODE REVIEW

**Comment by mmusgrov** [comment]
Ah you provided a fix. I too was also working on it, I just had test still to do.
I will review what you have provided but whatever the outcome the PR would need to add a test in https://github.com/jbosstm/narayana/tree/master/ArjunaJTA/jta/tests/classes/com/hp/mwtests/ts/jta/commitmarkable.

**Comment by mmusgrov** [comment]
@gaol Please sign the CLA over here (project name is JBoss Transactions): https://cla.jboss.org/index.seam

**Comment by mmusgrov** [comment]
TESTIT

**Comment by mmusgrov** [comment]
@gaol My fix ensured that all uses of CMR properties were dynamically read from the JTAEnvironmentBean.
I also added methods to JTAEnvironmentBean to avoid property changes interleaving:
``` java
    public void removeCommitMarkableResource(String jndiName) {
    public void addCommitMarkableResource(String jndiName, String tableName, boolean immediateCleanup, int batchSize) {
```

How does your PR relate to my approach?

**Comment by gaol** [comment]
@mmusgrov Sorry again that I don't know you are working on it currently, please go ahead with your approach because I am quite new to this project, and has definitely less knowledge about it. :smile: 

Here are summary of the changes in this PR, just FYI:

* Added `reloadRecoveryModules()` method in `RecoveryEnvironmentBean` and invoke it `PeriodicRecovery.loadModules()` method. this new method re-load the RecoveryModules forcibly, and it will be called when [ArjunaTransactionManagerService](https://github.com/wildfly/wildfly/blob/master/transactions/src/main/java/org/jboss/as/txn/service/ArjunaRecoveryManagerService.java#L135) is started in WildFly server. The `:reload` operation will lead to `ArjunaRecoveryManagerService.start()`, new `CommitMarkableResourceRecordRecoveryModule` instance will be created at this time.
* Change static fields in `CommitMarkableResourceRecordRecoveryModule`, `CommitMarkableResourceRecord`, `TransactionImple` to final instance fields, so that new instances of these classes will pick new values from `JTAEnvironmentBean`

The benefit of using `final` fields is one step less to get the environment information in run-time.

Because any changes in `/subsystem=transactions/commit-markable-resource=*` will lead to `reload-required` state in WildFly server, I think it would be enough to pick the new values after `:reload`.

From what I understand from your description on your fix, I think your approach will make these values all dynamic, and it makes the changes in `JTAEnvironmentBean` won't need `:reload` anymore.

**Comment by gaol** [comment]
suppressed by #1676

**Pull request closed without merging**
