### PR TITLE
JBTM-3829 jacoco-report throws error (and doesn't fail)

### PR DESCRIPTION
**Pull request by tomjenkinson**
(possibly partial) https://issues.redhat.com/browse/JBTM-3829

!CORE !TOMCAT !AS_TESTS !RTS JACOCO !XTS !QA_JTA !QA_JTS_OPENJDKORB !PERFORMANCE !LRA !DB_TESTS mysql db2 postgres oracle

### CODE REVIEW

**Comment by marcosgopen** [comment]
> I tried downloading artifacts from the build and ran a step here too to get some missing part but even then the ant step works for me locally. I have checked version of ANT and think that is the same so it's a bit of a mystery why it's failing on CI. I have put a commit in that would add debug from the ANT process. (note to any reviewers) I suppose I would back that out before merging so please consider in your review.

Could I also suggest you to temporary enable the verbose flag "-v"?

**Comment by marcosgopen** [comment]
> I think there is something in the log that seems useful:
> 
> ```
> <REDACT>/qa/run-tests.xml:561: Error while creating report
> 	at org.jacoco.ant.ReportTask.execute(ReportTask.java:502)
> 	at org.apache.tools.ant.UnknownElement.execute(UnknownElement.java:299)
> 	at jdk.internal.reflect.GeneratedMethodAccessor4.invoke(Unknown Source)
> 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
> 	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
> 	at org.apache.tools.ant.dispatch.DispatchUtils.execute(DispatchUtils.java:99)
> 	at org.apache.tools.ant.Task.perform(Task.java:350)
> 	at org.apache.tools.ant.Target.execute(Target.java:449)
> 	at org.apache.tools.ant.Target.performTasks(Target.java:470)
> 	at org.apache.tools.ant.Project.executeSortedTargets(Project.java:1401)
> 	at org.apache.tools.ant.Project.executeTarget(Project.java:1374)
> 	at org.apache.tools.ant.helper.DefaultExecutor.executeTargets(DefaultExecutor.java:41)
> 	at org.apache.tools.ant.Project.executeTargets(Project.java:1264)
> 	at org.apache.tools.ant.Main.runBuild(Main.java:818)
> 	at org.apache.tools.ant.Main.startAnt(Main.java:223)
> 	at org.apache.tools.ant.launch.Launcher.run(Launcher.java:284)
> 	at org.apache.tools.ant.launch.Launcher.main(Launcher.java:101)
> Caused by: java.io.IOException: Error while analyzing narayana-tomcat/tomcat-jta/target/lib/byteman.jar@org/jboss/byteman/rule/expression/NewExpression.class with JaCoCo 0.8.8.202204050719/5dcf34a.
> 	at org.jacoco.core.analysis.Analyzer.analyzerError(Analyzer.java:163)
> 	at org.jacoco.core.analysis.Analyzer.analyzeClass(Analyzer.java:135)
> 	at org.jacoco.core.analysis.Analyzer.analyzeClass(Analyzer.java:158)
> 	at org.jacoco.core.analysis.Analyzer.analyzeAll(Analyzer.java:195)
> 	at org.jacoco.core.analysis.Analyzer.analyzeZip(Analyzer.java:267)
> 	at org.jacoco.core.analysis.Analyzer.analyzeAll(Analyzer.java:198)
> 	at org.jacoco.ant.ReportTask.createBundle(ReportTask.java:573)
> 	at org.jacoco.ant.ReportTask.createReport(ReportTask.java:545)
> 	at org.jacoco.ant.ReportTask.execute(ReportTask.java:496)
> 	... 16 more
> Caused by: java.lang.IllegalStateException: Can't add different class with same name: org/jboss/byteman/rule/expression/NewExpression
> 	at org.jacoco.core.analysis.CoverageBuilder.visitCoverage(CoverageBuilder.java:106)
> 	at org.jacoco.core.analysis.Analyzer$1.visitEnd(Analyzer.java:100)
> 	at org.objectweb.asm.ClassVisitor.visitEnd(ClassVisitor.java:377)
> 	at org.jacoco.core.internal.flow.ClassProbesAdapter.visitEnd(ClassProbesAdapter.java:100)
> 	at org.objectweb.asm.ClassReader.accept(ClassReader.java:748)
> 	at org.objectweb.asm.ClassReader.accept(ClassReader.java:424)
> 	at org.jacoco.core.analysis.Analyzer.analyzeClass(Analyzer.java:117)
> 	at org.jacoco.core.analysis.Analyzer.analyzeClass(Analyzer.java:133)
> 	... 23 more
> ```

Thanks @tomjenkinson  for analyzing this.  I remember I encountered that error "Can't add different class with same name" And I remember I had to remove many and many dependencies (not only narayana-tomcat) from the jacoco-generator set of dependencies to be scanned before seeing it passing. @jmfinelli helped me with that at the time, but eventually I couldn't find a proper solution for it (excluding so many dependencies was not what we wanted to).

**Comment by jmfinelli** [comment]
> Thanks @tomjenkinson for analyzing this. I remember I encountered that error "Can't add different class with same name" And I remember I had to remove many and many dependencies (not only narayana-tomcat) from the jacoco-generator set of dependencies to be scanned before seeing it pass. @jmfinelli helped me with that at the time, but eventually I couldn't find a proper solution for it (excluding so many dependencies was not what we wanted to).

Yep, I think that's why I ended up discovering [MavenMultiModule](https://github.com/jacoco/jacoco/wiki/MavenMultiModule)

**Comment by marcosgopen** [comment]
> Did you try to disable Tomcat in the manner I have started to try to (by not running TOMCAT_TESTS)?

No, we tried to add that folder into the exclusion set: https://github.com/jbosstm/narayana/blob/main/qa/run-tests.xml#L568-L589

**Comment by marcosgopen** [comment]
> Thanks for the info @marcosgopen - did you manage to see if failing locally at all? And if you did get it to fail locally was it by using narayana.sh or calling say `ant` commands directly?

Yes, I saw it fail locally too. Let me find again the proper reproducer.

**Comment by marcosgopen** [comment]
> :( @marcosgopen it worked for me with my branch, and with your version with a couple of changes to what you have (but still primarily what you have) and to use JDK 11. The code changes to what you have was a rebase on main and a commit to partially revert a bit how you did the ow2 (please look in [marcosgopen/narayana@marcosgopen:JBTM-3829...tomjenkinson:narayana:marco-JBTM-3829](https://github.com/marcosgopen/narayana/compare/marcosgopen:JBTM-3829...tomjenkinson:narayana:marco-JBTM-3829) and in particular `c8d2410916fc0c6dfc97f50c1777d9a20ee8cc4d`. Maybe I didn't run it long enough but for your case, on the environment from what you shared in your info, I am wondering about the existence of `.../bin/target/...` in your path. It's not a normal build I think (I think from IDE output) and maybe could account for the duplicates you saw: `ArjunaCore/arjunacore/bin/target/arjunacore-7.0.1.Final-SNAPSHOT.jar` (do you have a `ArjunaCore/arjunacore/target/arjunacore-7.0.1.Final-SNAPSHOT.jar` as well in the path?)?
> 
> Output for me:
> 
> ```
> $ ant -f run-tests.xml jacoco-report -v
> Apache Ant(TM) version 1.10.12 compiled on July 19 2023
> Buildfile: <REDACT/>/qa/run-tests.xml
> Detected Java version: 11 in: /usr/lib/jvm/java-11-openjdk-11.0.22.0.7-1.fc39.x86_64
> Detected OS: Linux
> parsing buildfile <REDACT/>/qa/run-tests.xml with URI = file:<REDACT/>/qa/run-tests.xml
> Project base dir set to: <REDACT/>/qa
> parsing buildfile jar:file:/usr/share/java/ant/ant.jar!/org/apache/tools/ant/antlib.xml with URI = jar:file:/usr/share/java/ant/ant.jar!/org/apache/tools/ant/antlib.xml from a zip file
> parsing buildfile jar:file:<REDACT/>/qa/ext/ant-contrib.jar!/net/sf/antcontrib/antlib.xml with URI = jar:file:<REDACT/>/qa/ext/ant-contrib.jar!/net/sf/antcontrib/antlib.xml from a zip file
> parsing buildfile jar:file:<REDACT/>/qa/ext/org.jacoco.ant.jar!/org/jacoco/ant/antlib.xml with URI = jar:file:<REDACT/>/qa/ext/org.jacoco.ant.jar!/org/jacoco/ant/antlib.xml from a zip file
>  [property] Loading Environment env.
>  [macrodef] creating macro  junit-tests
> Build sequence for target(s) `jacoco-report' is [check-jacoco-data, jacoco-report]
> Complete build sequence is [check-jacoco-data, jacoco-report, junit-testsuite, ci-junit-testsuite, jta, junit-jdbc-crachrec, junit-jdbc-testsuite, junit-jdbc, junit-jts-testsuite, ci-tests, core-memory, onetest, has-testoutput-output, performance, ci-tests-nojts, testoutput.zip, ci-jts-tests, scratch, test, express, junit, ]
> 
> check-jacoco-data:
> [available] Found: testoutput/jacoco-qa.exec
> 
> jacoco-report:
> [antlib:org.jacoco.ant] Could not load definitions from resource org/jacoco/ant/antlib.xml. It could not be found.
> [jacoco:report] Loading execution data file <REDACT/>/qa/testoutput/jacoco-qa.exec
> [jacoco:report] Writing bundle 'Narayana QA Report' with 1830 classes
> 
> BUILD SUCCESSFUL
> Total time: 5 seconds
> ```

Thanks @tomjenkinson , that was an error on my side. I had duplicated 'target' in bin/target and target folders (probably due to my IDE). Now it works fine! I will retry with your branch and review your PR.

**Review by marcosgopen — APPROVED** [review]
Thanks @tomjenkinson for your PR!

**Review by marcosgopen — APPROVED** [review]
Thanks @tomjenkinson for your PR and raising the issue.

**Pull request merged**
