### PR TITLE
[JBTM-3478] Added SortPom to narayana-all and activated it by default

### PR DESCRIPTION
**Pull request by jmfinelli**
This PR addresses JIRA [JBTM-3478](https://issues.redhat.com/browse/JBTM-3478)

Profiles passed:
!MAIN !CORE

Profiles to skip:
!TOMCAT !AS_TESTS !RTS !JACOCO !XTS !QA_JTA !QA_JTS_JACORB !QA_JTS_JDKORB !QA_JTS_OPENJDKORB !BLACKTIE !PERF !LRA NO_WIN !DB_TESTS !mysql !db2 !postgres !oracle

### CODE REVIEW

**Review by ochaloup — APPROVED** [review]
Nice :-)

**Review by mmusgrov — DISMISSED** [review]
The process for changing the code base is to raise an issue describing the problem and only then to raise a PR that demonstrates to other readers that the proposed changes correctly address the issue. Without that is isn't possible to demonstrate the issue is fixed

I will add these details the help text we display on new pull requests.

**Comment by jmfinelli** [comment]
> [..] to raise an issue describing the problem [..]

I have added a description to [JBTM-3478](https://issues.redhat.com/browse/JBTM-3478). The main reason to introduce SortPom in the Narayana code base is to enforce consistency in `pom.xml` files

**Review by ochaloup — APPROVED** [review]
Seems fine to me.

**Pull request merged**
