### PR TITLE
[JBTM-2925] adding db2 driver name to jdbc driver list

### PR DESCRIPTION
**Pull request by ochaloup**
The list checks what the jdbc connection DatabaseMetaData.getDriverName() gets.
Adding string returned by jdbc driver from DB2 database.

This is per discussion from with Tom and @domhanak.

!QA_JTS_JDKORB !QA_JTS_OPENJDKORB !QA_JTS_JACORB !BLACKTIE !PERF NO_WIN !RTS !XTS

### CODE REVIEW

**Comment by ochaloup** [comment]
@tomjenkinson sure, ok

**Comment by domhanak** [comment]
@ochaloup @tomjenkinson I managed to fix the DB2 without these changes, the problem was that I didn't properly set these 2 properties - resultSetHoldability=1 and downgradeHoldCursorsUnderXa=true. After setting them in the driver via reflection everything seems to work.

**Comment by domhanak** [comment]
Well, in logs I found this error:
 `com.ibm.db2.jcc.am.SqlException: [jcc][t4][10120][10898][4.19.26] Invalid operation: result set is closed. ERRORCODE=-4470, SQLSTATE=null` 
I found about it on ibm developers [forum](https://developer.ibm.com/answers/questions/194821/invalid-operation-result-set-is-closed-errorcode-4.html)

**Comment by domhanak** [comment]
@tomjenkinson what docs are you talking about? :)

**Comment by ochaloup** [comment]
@domhanak interesting. btw. those connection properties should be set in WFLY datasource configuration, I think.

**Pull request merged**
