### PR TITLE
[JBTM-3710] QA's building system updated

### PR DESCRIPTION
**Pull request by jmfinelli**
This PR addresses [JBTM-3710](https://issues.redhat.com/browse/JBTM-3710)

JDK17 CORE  QA_JTA QA_JTS_OPENJDKORB
!TOMCAT !AS_TESTS !RTS !JACOCO !XTS !PERF !LRA !DB_TESTS !mysql !db2 !postgres !oracle

### CODE REVIEW

**Review by marcosgopen — APPROVED** [review]
Thanks @jmfinelli for you PR, it simplifies QA and removing redundant code makes QA more understandable.
Please could you add some info on classes "**/${astest.dir}/**/*.java" that have been removed in the Jira
https://issues.redhat.com/browse/JBTM-3710
Thanks again!

**Comment by jmfinelli** [comment]
Thanks for your review @marcosgopen!

I had another look at `astests`: they are integration tests that used to be run using WFLY. What kind of info would you like to add to the JIRA?

**Comment by marcosgopen** [comment]
> Thanks for your review @marcosgopen!
> 
> I had another look at `astests`: they are integration tests that used to be run using WFLY. What kind of info would you like to add to the JIRA?

I think it might be helpful to describe the reason why those unused tests can be removed and don't need to be restored. Thanks

**Comment by jmfinelli** [comment]
@marcosgopen I have added a comment to [JBTM-3710](https://issues.redhat.com/browse/JBTM-3710). Could you please double check if it addresses your request? Thanks

**Comment by marcosgopen** [comment]
Thanks @jmfinelli . Yes, it does. Thanks again for your PR!

**Pull request merged**
