### PR TITLE
JBTM-3177 Rename lra-filters module to narayana-lra

### PR DESCRIPTION
**Pull request by xstefank**
https://issues.jboss.org/browse/JBTM-3177

!QA_JTA !QA_JTS_JDKORB !QA_JTS_OPENJDKORB !QA_JTS_JACORB !BLACKTIE !XTS !PERF NO_WIN !AS_TESTS !TOMCAT !JACOCO !mysql !postgres !db2 !oracle !RTS

### CODE REVIEW

**Comment by xstefank** [comment]
@tomjenkinson will you start the discussion in the forum or should I do it?

**Comment by xstefank** [comment]
Forum reference - https://developer.jboss.org/message/990654#990654

**Comment by xstefank** [comment]
interesting, I passed the TCK with this yesterday, but it probably took my local version of lra-filters still. 

retest this please

**Comment by mmusgrov** [comment]
@xstefank Can you also raise a PR on https://github.com/jbosstm/quickstart/pulls too please

**Comment by xstefank** [comment]
quickstart PR - https://github.com/jbosstm/quickstart/pull/256

**Pull request merged**
