### PR TITLE
[RELEASE][5.11 branch] fix Narayana version to work with 5.11 SNAPSHOT

### PR DESCRIPTION
**Pull request by ochaloup**
QA_JTA QA_JTS_JDKORB
!MAIN !CORE !QA_JTS_OPENJDKORB !QA_JTS_JACORB !BLACKTIE !XTS !PERF NO_WIN !RTS !AS_TESTS !TOMCAT !JACOCO !LRA

### CODE REVIEW

**Comment by mmusgrov** [comment]
@ochaloup the qa builds seem to be failing with `Caused by: java.lang.ClassNotFoundException: com.arjuna.orbportability.ORB`. I do notice that the qa test suite is looking for narayana in `dist/narayana-full-5.11.2.Final`, ie one or more of the build scripts under qa will also need looking at.

**Comment by ochaloup** [comment]
I slowly moving from `failing everything` to `failing only jdbc tests`. I'm backporting the change from @jmfinelli about JDBC oracle drivers. I hope it will be working completely now.

**Review by mmusgrov — COMMENTED** [review]
scripts/hudson/narayana.sh still contains a reference to the older version.
blacktie still references 5.11.2

@jmfinelli could you review this PR and check the backport of the fix you made for the oracle driver.

**Comment by mmusgrov** [comment]
@ochaloup removing BlackTie from maintenance branches is also an option since we don't support BlackTie (or just make sure it is disabled).

**Comment by ochaloup** [comment]
@mmusgrov alright, I fixed the wrong version in `narayana.sh`. Thanks.
I would leave the blacktie as part of the branch as it was part of the branch when we released the 5.11.2.Final (the time the 5.11 branch was created).

**Review by jmfinelli — APPROVED** [review]
About the oracle driver, It looks good to me :+1:
Just a question: I guess we do not want to back port the other DB drivers, do we?

**Comment by mmusgrov** [comment]
@jmfinelli That's a good point, where is the JIRA/PR for that change?

**Comment by jmfinelli** [comment]
> @jmfinelli That's a good point, where is the JIRA/PR for that change?

[[JBTM-3480] Change the logic to download DB drivers in the QA module](https://github.com/jbosstm/narayana/pull/1845/)

**Comment by mmusgrov** [comment]
I thought we only had had an issue with the oracle driver, did you have to update any of the other drivers?

**Comment by jmfinelli** [comment]
> I thought we only had had an issue with the oracle driver, did you have to update any of the other drivers?

That is correct, we had an issue only with the oracle driver. The JIRA [JBTM-3480](https://issues.redhat.com/browse/JBTM-3480) addressed a problem for the community: the old logic to fetch DB drivers in the QA module relied on a (VPN) Red Hat server (currently offline anyway). With the new logic introduced in JBTM-3480, DB drivers are now downloaded through Maven. As a consequence, the community can run QA tests (nearly) out-of-the-box

**Review by mmusgrov — APPROVED** [review]

**Comment by mmusgrov** [comment]
It was a good change. Since we don't need to backport to the maintenance branches I believe we can merge now, thanks.

**Pull request merged**
