### PR TITLE
JBTM-2523 Upgrade the activemq-artimes to 1.1.0-wildfly-6

### PR DESCRIPTION
**Pull request by zhfeng**
https://issues.jboss.org/browse/JBTM-2523

!BLACKTIE !XTS !QA_JTA !QA_JTS_JACORB !PERF

### CODE REVIEW

**Comment by zhfeng** [comment]
The failure is related to the cmr integration tests and it should be re-test after fixing the JBTM-2524

**Comment by mmusgrov** [comment]
This looks like a duplicate of JBTM-2520. Can you rebase your PR and retest.

**Comment by zhfeng** [comment]
No, I comment on JBTM-2524 and it looks like that the wildfly standalone-full.xml has some changes again

**Comment by zhfeng** [comment]
see https://github.com/wildfly/wildfly/commit/5b470a7e824336d0b3cb5f5dba18f6a254c7dae0 
The message-activemq subsystem template has some changes on the endpoint.

**Pull request merged**
