### PR TITLE
[JBTM-3216] narrow and fix recovery setup in jbossts-properties.xml descriptors

### PR DESCRIPTION
**Pull request by ochaloup**
https://issues.jboss.org/browse/JBTM-3216
forum at: https://developer.jboss.org/message/991332

MAIN QA_JTA QA_JTS_OPENJDKORB
!QA_JTS_JDKORB !QA_JTS_JACORB !BLACKTIE !XTS !PERF NO_WIN !RTS !AS_TESTS !TOMCAT !JACOCO !LRA

### CODE REVIEW

**Comment by mmusgrov** [comment]
Do you have any evidence to justify this change of behaviour. If none of our users and stakeholders have reported an issue I think we need to be cautious about removing filters.

**Comment by ochaloup** [comment]
@mmusgrov yes. The filters are put wrongly as nobody was caring how they are defined in the xml descriptors.
If you have some worries, I'm really interested in. Just, please, comment on the particular change/filter. Thanks.

**Comment by mmusgrov** [comment]
> @mmusgrov yes. The filters are put wrongly as nobody was caring how they are defined in the xml descriptors.
> If you have some worries, I'm really interested in. Just, please, comment on the particular change/filter. Thanks.

I was referring to the removal of filters:

1. Will removing a filter change the behaviour for the end use?
2. How do you know that it is safe to remove a filter?
3. Why do you need to remove a filter - is there a question/issue raised by a community member due to the presence of the filter?
4. Is the functionality provided by the removed filter available elsewhere or is it simply not required anymore?

**Comment by ochaloup** [comment]
Thanks @mmusgrov.

I consider this could be merged as reviewed by Mike and the changes reflects our discussion with @tomjenkinson at the forum.

**Pull request merged**
