### PR TITLE
[JBTM-3117] Upgrade to the latest LRA spec version

### PR DESCRIPTION
**Pull request by xstefank**
https://issues.jboss.org/browse/JBTM-3117

!QA_JTA !QA_JTS_JDKORB !QA_JTS_OPENJDKORB !QA_JTS_JACORB !BLACKTIE !XTS !PERF NO_WIN !AS_TESTS !TOMCAT !JACOCO !mysql !postgres !db2 !oracle

### CODE REVIEW

**Comment by mmusgrov** [comment]
I am in the middle of upgrading the TCK which subsumes the changes made in this PR. Please can I make this set of changes, I should be ready by Monday/Tues. Thanks

**Comment by xstefank** [comment]
@mmusgrov sure, go ahead

**Comment by mmusgrov** [comment]
@xstefank I am still debugging 6 TCK tests so won't be ready today. If you are stalled waiting for me then let me know and I will approve this PR.

**Comment by xstefank** [comment]
@mmusgrov it's ok from my side

**Comment by mmusgrov** [comment]
Please ignore the MAIN and BLACKTIE profile tests. I was setting up a PR poller job on our Jenkins installation. I temporarily added a build periodically schedule and it started retesting all the PRs. Since the job config was incorrect it rapidly cycled through old PRs before I was able to stop it. Sorry about that. It is disabled now.

**Pull request merged**
