### PR TITLE
JBTM-2901 skip recovery pass 2 if it has already ran

### PR DESCRIPTION
**Pull request by mmusgrov**
https://issues.jboss.org/browse/JBTM-2901

!BLACKTIE !XTS !QA_JTA !QA_JTS_JACORB !QA_JTS_JDKORB !PERF !RTS

### CODE REVIEW

**Comment by gytis** [comment]
There is still something missing. XARecoveryModule second pass invoked by PeriodicRecovery comes from an IDLE state and is ignored. Let me try to put together a reproducer which is easier to run, so I could share it with you.

**Comment by mmusgrov** [comment]
Yes but those other narayana changes relate to a different PR: https://github.com/jbosstm/narayana/pull/1182

I am asking you to just review the change we discussed via email.

**Comment by mmusgrov** [comment]
If is ok because the following sequence of events has occurred:

pass 1 is called (by periodic recovery) and then something else calls getNewXAResource which calls pass 2. Now when periodic recovery calls pass 2 the XARecoveryModule says, oh I have just done pass 2 so I will return without doing anything.

**Comment by gytis** [comment]
OK understood. I'll look into updating Spring Boot integration to function with this change.

**Pull request merged**
