### PR TITLE
[RELEASE][5.11] changes the scripts to follow the 5.11 branch release processing

### PR DESCRIPTION
**Pull request by ochaloup**
MAIN AS_TESTS
!QA_JTA !QA_JTS_JDKORB !QA_JTS_OPENJDKORB !QA_JTS_JACORB !BLACKTIE !XTS !PERF NO_WIN !RTS !TOMCAT !JACOCO !LRA

### CODE REVIEW

**Review by mmusgrov — APPROVED** [review]
These are invaluable changes.
Do we need an update to the Narayana-Release-Process guide on our wiki?

**Comment by ochaloup** [comment]
New changes: I changed the scripts to rebase correctly against the 5.11 branch and added job 511-AS_TESTS to be checked on release.

@mmusgrov agree about the wiki. I need to check how to change the text there. I'm working on it.

**Comment by mmusgrov** [comment]
The changes you just added still look good but I will take another look when the CI run finishes.

**Comment by mmusgrov** [comment]
Your changes still look good (and I see that the de-emphasis of BlackTie is picking up momentum ;-))

**Comment by ochaloup** [comment]
The wiki was updated. With adjusting the text I found my changes were missing to upload artifacts to `jboss.org downloads`. The new push has fixed it.

This should be the final version of this PR. Sorry for the email spamming from the github because of the subsequent changes.

**Comment by mmusgrov** [comment]
Getting it accurate is better than coping with a bit of extra spam :-)

**Comment by mmusgrov** [comment]
The AS_TESTS failures seem unrelated:
  DatabaseTimerServiceMultiNodeTestCase.testEjbTimeoutOnOtherNode
  Integration - Elytron
so my approval still stands

**Comment by ochaloup** [comment]
@mmusgrov agree, the AS_TESTS are unrelated. The point of this change was to get running the 5.11 branch against the `5_11_BRANCH/23.x` of WildFly. As it was started it's fine and the tests failures are unrelated. Thank you for the review.

**Pull request merged**
