### PR TITLE
Revert 4 commits

### PR DESCRIPTION
**Pull request by gytis**
Uses https://github.com/jbosstm/jboss-as/pull/60
!BLACKTIE !MAIN !QA_JTA !QA_JTS_JDKORB !PERF

### CODE REVIEW

**Comment by mmusgrov** [comment]
Is there an associated JIRA or documented reason for the revert?

**Comment by gytis** [comment]
Tom want's to make a release for EAP 7.1. And compensations recovery should go for WildFly 11

**Comment by gytis** [comment]
We'll move them back in after the release

**Comment by mmusgrov** [comment]
Thanks

**Pull request merged**
