### PR TITLE
JBTM-3543 Replace confusing log message with something more appropriate

### PR DESCRIPTION
**Pull request by mmusgrov**
https://issues.redhat.com/browse/JBTM-3543

MAIN CORE !QA_JTA !QA_JTS_JDKORB !QA_JTS_OPENJDKORB !QA_JTS_JACORB !BLACKTIE !XTS !PERF !LRA NO_WIN !RTS !AS_TESTS !TOMCAT !JACOCO

### CODE REVIEW

**Comment by mmusgrov** [comment]
@jmfinelli CI did run (btny-pulls-narayana/239/) for this PR, just it has not updated the PR.

**Review by jmfinelli — APPROVED** [review]

**Comment by jmfinelli** [comment]
@mmusgrov CORE was turned off (i.e. !CORE). Testing this PR again but I have the feeling it will pass ;-)

**Comment by mmusgrov** [comment]
So we need to update `PULL_REQUEST_TEMPLATE.md`.

**Comment by jmfinelli** [comment]
I agree...+1

**Pull request merged**
