### PR TITLE
JBTM-3391 LRA Transaction#isInEndState method can fail the LRA if fai…

### PR DESCRIPTION
**Pull request by xstefank**
…ledList is not created before

https://issues.redhat.com/browse/JBTM-3391

!MAIN !TOMCAT !AS_TESTS !RTS !JACOCO !XTS !QA_JTA !QA_JTS_JACORB !QA_JTS_JDKORB !QA_JTS_OPENJDKORB !BLACKTIE !PERF LRA NO_WIN !DB_TESTS !MySQL !db2 !postgres !oracle

### CODE REVIEW

**Review by ochaloup — APPROVED** [review]
Could this be covered in some test?

**Comment by xstefank** [comment]
@ochaloup I mentioned the "failing" test in the JIRA. We can't assure that the LRA is closed in the end because it's removed from the OS if closed successfully. But we can have test that checks that it's not present in the failed list. Not sure if it's worth it TBH.

**Comment by mmusgrov** [comment]
Yes I know about this one, my fix for pr #1717 is already including that change so I'd prefer to close this pr.

**Comment by xstefank** [comment]
@mmusgrov I don't see changes from this PR in #1717. So I suppose you mean merged not closed?

**Comment by mmusgrov** [comment]
I am putting this one on hold so that we don't inadvertently merge it (the fix is in the other PR https://github.com/jbosstm/narayana/pull/1717/files#diff-249046e2280be10c594de80e96d41fff9e00eccbb98d6e40a5cf19138714b208R613).

**Comment by xstefank** [comment]
it would be totally fine to merge this and rebase your PR. But if you need all changes in one commit that came after my PR then you can close this PR.

**Comment by mmusgrov** [comment]
> @mmusgrov it would be totally fine to merge this and rebase your PR. But if you need all changes in one commit that came after my PR then you can close this PR.

The defect was exposed by my PR #1717 which was testing for LRA parent context propagation.
The failure only came to light because your test (NestedParticipantIT#nestedParticipantAfterLRACallTest) failed and my code changes had uncovered this particular code route (where the failureList was uninitialised).
I didn't expect you to try fixing it since the problem was in my PR.
If reviewers start trying to fixing other peoples PR test failures when they are still working on them then it makes work management more difficult.

**Comment by xstefank** [comment]
linked JIRA points to the test that I've run into this issue - https://issues.redhat.com/browse/JBTM-3391 -> https://issues.redhat.com/browse/JBTM-3387 which is NarayanaLRAClientIT#testGetAllLRAs. So we did the same fix in "parallel" where I made a PR first. As I said, if you want everything in a single PR then go ahead and close my work (PR + JIRA).

**Comment by mmusgrov** [comment]
rejecting as a duplicate

**Pull request closed without merging**
