### PR TITLE
CODEOWNERS removed

### PR DESCRIPTION
**Pull request by jmfinelli**
CODEOWNERS removed

NO_TEST

### CODE REVIEW

**Comment by marcosgopen** [comment]
Thanks @jmfinelli for your PR. Without the codeowner file we need to remember to ask for a review to some Narayana's team member. Could you confirm this 'process' is properly described in the contributing file?

**Comment by jmfinelli** [comment]
It looks like -> https://github.com/jbosstm/narayana/blob/main/CONTRIBUTING.md#code-reviews

**Review by marcosgopen — APPROVED** [review]
Thanks @jmfinelli

**Comment by jmfinelli** [comment]
> @jmfinelli Will you update the spreadsheet adding a note saying why and also add a comment to the OKR issue.

No problem :-)

**Comment by marcosgopen** [comment]
@mmusgrov @jmfinelli Do you all agree to remove the CODEOWNER file from jbosstm/quickstart repo too? If so, I will remove it then.

**Comment by jmfinelli** [comment]
Wasn't this PR merged?

**Comment by mmusgrov** [comment]
> @mmusgrov @jmfinelli Do you all agree to remove the CODEOWNER file from jbosstm/quickstart repo too? If so, I will remove it then.

Yes, let's remove it from that one too.

**Pull request merged**
