### PR TITLE
JBTM-3130 Update JNDI manager for newer mysql and oracle drivers

### PR DESCRIPTION
**Pull request by istraka**
https://issues.jboss.org/browse/JBTM-3130

!MAIN !QA_JTS_JDKORB !QA_JTS_OPENJDKORB !QA_JTS_JACORB !BLACKTIE !XTS !PERF NO_WIN !RTS !AS_TESTS !TOMCAT !JACOCO !LRA DB_TESTS mysql postgres db2 oracle

### CODE REVIEW

**Comment by ochaloup** [comment]
@istraka I see this is a small change but would you be so kind and create a new JIRA for this fix? It would be good for the later times to know what was the motivation behind the change. The summary of the jira will provide so.

**Comment by istraka** [comment]
@ochaloup  sure, I have updated the title of the PR.

**Comment by ochaloup** [comment]
@istraka great, can you please change the message of the git commit as well please?

**Comment by istraka** [comment]
@ochaloup done

**Pull request merged**
