### PR TITLE
JBTM-3516 fix passing parameters with spaces in build.sh

### PR DESCRIPTION
**Pull request by RanabirChakraborty**
Issue: https://issues.redhat.com/browse/JBTM-3516

### CODE REVIEW

**Review by mmusgrov — COMMENTED** [review]
Although the changes look okay, we have never had any issues with globbing in this script over many years of usage. Can you update the JIRA with an explanation of which usages fail (ie a reproducer).

**Comment by RanabirChakraborty** [comment]
@mmusgrov sure I have just now added a sample execution, using that we'll be able to see the error.

**Review by mmusgrov — APPROVED** [review]
Well spotted and thanks also for the updating the JIRA with an example of the problem.
The contribution is appreciated.

**Comment by RanabirChakraborty** [comment]
Thank you! :)

**Comment by RanabirChakraborty** [comment]
Thank you! :)

**Pull request merged**
