### PR TITLE
JBTM-3414 Update to add null check with trans on Xids trace logging d…

### PR DESCRIPTION
**Pull request by zhfeng**
…uring xaRecoveryFirstPass

https://issues.redhat.com/browse/JBTM-3414

MAIN CORE !TOMCAT !AS_TESTS !RTS !JACOCO !XTS !QA_JTA !QA_JTS_JACORB !QA_JTS_JDKORB !QA_JTS_OPENJDKORB !BLACKTIE !PERF !LRA !NO_WIN DB_TESTS !mysql !db2 !postgres !oracle

### CODE REVIEW

**Review by ochaloup — APPROVED** [review]
Seems fine to me.

**Comment by zhfeng** [comment]
Thanks @ochaloup !

**Comment by mmusgrov** [comment]
@ochaloup how does this pr relate to [JBTM-3383] Improve ARJUNA016009: Caught::java.lang.NullPointerException log message

**Comment by mmusgrov** [comment]
@ochaloup in particular, does it obsolete pr #1747 [JBTM-3383]

**Comment by ochaloup** [comment]
@mmusgrov I would say the pr #1747 elaborates on the NPE issue and fixes it in the broader scope. This PR and the pr #1747 touches the same part of the code.

**Comment by mmusgrov** [comment]
@ochaloup I thought the issue was that the logging code is throwing an NPE which, although it does not cause any functional issues, it makes EAP look bad because it suggests a problem in EAP. Why do we have two issues and two PRs for the same (non functional) problem?

**Comment by zhfeng** [comment]
@mmusgrov JBTM-3414 came across the Fuse case and I have no idea about  JBTM-3383. Maybe we can mark JBTM-3413 as duplicated ?

**Comment by mmusgrov** [comment]
@zhfeng thanks for the fix, I am investigating why we ended up with two JBTM's for this issue.

**Comment by mmusgrov** [comment]
But ideally we should have caught the duplication before merging the fixes.

**Comment by ochaloup** [comment]
@mmusgrov trace logging caused the functional issue as well. But it was caused by fact the trace logging is switched on. The trouble with NPE would probably not be considered in full scope if @zhfeng does not raise this one.

**Pull request merged**
