### PR TITLE
[JBTM-3442] transactional cdi InterceptionFactory

### PR DESCRIPTION
**Pull request by ochaloup**
https://issues.redhat.com/browse/JBTM-3442

MAIN AS_TESTS
!QA_JTA !QA_JTS_JDKORB !QA_JTS_OPENJDKORB !QA_JTS_JACORB !BLACKTIE !XTS !PERF NO_WIN !RTS !TOMCAT !JACOCO !LRA

@manovotn could you, please, take a look at this PR?

### CODE REVIEW

**Review by manovotn — COMMENTED** [review]
Yeah, looks good to me.

@ochaloup the only issue I see is that non-weld impl will still blow up with hard to read error (I think it was NPE?). It might be worth guarding for that `null` and rethrowing something more understandable. Can even be something like "not supported for interception factory with non-weld CDI impl". But it is OFC up to you; I have no idea in which environments is Narayana usually used.

**Comment by mmusgrov** [comment]
@manovotn narayana is used by many products (quarkus, fuse osgi, wildfly, etc) so throwing the exception early is preferable.

**Comment by ochaloup** [comment]
@manovotn thanks, that's a really good point. I added a check on `null` in the problematic place. Please, take a look if you consider it fine or to be refined.

**Review by manovotn — APPROVED** [review]
LGTM now

**Review by mmusgrov — APPROVED** [review]
I think Matej's approval is sufficient.

**Comment by ochaloup** [comment]
the CI tests seem fine, the AS_TESTS fails with the intermittent failure at `DatabaseTimerServiceMultiNodeTestCase.testEjbTimeoutOnOtherNode`
it's the CI issue. it's something that I'm trying to hit with other testing job and find if some timeout adjust may help but I'm not able so far to say where the trouble is

**Comment by ochaloup** [comment]
@manovotn thanks!

**Pull request merged**
