### PR TITLE
[JBTM-3673] Removed maven profile jdk17 and updated Arquillian dependencies

### PR DESCRIPTION
**Pull request by jmfinelli**
Addresses [JBTM-3673](https://issues.redhat.com/browse/JBTM-3673)

To test:
JDK17 LRA AS_TESTS RTS 

Passed
!XTS !JACOCO !JDK11 !CORE !TOMCAT !QA_JTA !QA_JTS_OPENJDKORB PERF !DB_TESTS !mysql !db2 !postgres !oracle

### CODE REVIEW

**Review by mmusgrov — APPROVED** [review]
The arquillian changes look fine.
I did not understand the JDK 17 changes but I assume you known why they need removing and I trust your judgement so I'm approving.
@jmfinelli What is the status of this PR regarding the Hold label?

**Comment by jmfinelli** [comment]
I have another commit to push but (unfortunately) there is a jdk17 profile that needs the migration to Jakarta to be removed (I hope). I was waiting that we migrate Narayana to Jakarta before going back to this PR. WDYT?

**Comment by mmusgrov** [comment]
> I have another commit to push but (unfortunately) there is a jdk17 profile that needs the migration to Jakarta to be removed (I hope). I was waiting that we migrate Narayana to Jakarta before going back to this PR. WDYT?

Sounds good, thanks

**Comment by jmfinelli** [comment]
Even though this PR is ready to be merged, I decided to `hold` it until we can test its changes with Narayana 6.0

**Comment by jmfinelli** [comment]
This PR has been updated. As MP LRA TCK uses an older version of Arquillian (i.e. 1.7.0.Alpha9), the jdk17 profile (i.e. the usage of add-opens) is still needed in the module `rts/lra/test/tck/pom.xml`. I opened a new issue to track the removal of this profile from `rts/lra/test/tck/pom.xml` once MP LRA TCK starts using Arquillian 1.7.0.Alpha12.

**Pull request merged**
