### PR TITLE
[JBTM-3489] REST-AT annotation demo ends in the wrong state

### PR DESCRIPTION
**Pull request by moulalis**
Issue: https://issues.redhat.com/browse/JBTM-3489

CORE TOMCAT AS_TESTS RTS JACOCO XTS QA_JTA QA_JTS_OPENJDKORB PERFORMANCE LRA DB_TESTS mysql db2 postgres oracle

### CODE REVIEW

**Review by marcosgopen — APPROVED** [review]
Thanks @moulalis  for your PR.  For giving a little bit of context this issue was discussed on zulip (https://narayana.zulipchat.com/#narrow/stream/323715-developers/topic/JBTM-3489-REST-AT.20annotation.20demo.20ends.20in.20the.20wrong.20state) and to better describe the issue Michael wrote: "So the fix is to write the microservices so that they follow the RESTAT protocol correctly - in particular in the method SRAParticipant.java#updateState the switch statement needs to check for TransactionPrepared and return 200 if it is able to prepare the work". Link to the Specification code is https://github.com/jbosstm/narayana/blob/4d7327a7124b54f46814e2102cf10bee6fa44f42/rts/at/tx/src/test/java/org/jboss/jbossts/star/test/SpecTest.java where you can find the valid return codes.
Since this demo will be moved in the quickstart repo it is up to you to review the README here or in the issue https://issues.redhat.com/browse/JBTM-3462.
When reviewing the README could I ask you to add there also the expected output (i.e. in my terminal the sra-partecipant logs `SRA: 0_ffff7f000001_83ccf69_645a0fa1_69: Updating hotel participant state to: TransactionPreparedSRA: 0_ffff7f000001_83ccf69_645a0fa1_69: Updating trip participant state to: TransactionPreparedSRA: 0_ffff7f000001_83ccf69_645a0fa1_69: Updating trip participant state to: TransactionCommittedSRA: 0_ffff7f000001_83ccf69_645a0fa1_69: Updating hotel participant state to: TransactionCommitted`)?

**Comment by moulalis** [comment]
> 

Hi @marcosgopen I've already updated the README in https://issues.redhat.com/browse/JBTM-3462 and [PR](https://github.com/jbosstm/quickstart/pull/434/files#diff-4f19a89bb38688ea426851c9baaadd98181c4e978d64014601539874ed88ca5fR32)

**Comment by mmusgrov** [comment]
> Thanks @moulalis for your PR. For giving a little bit of context this issue was discussed on zulip (https://narayana.zulipchat.com/#narrow/stream/323715-developers/topic/JBTM-3489-REST-AT.20annotation.20demo.20ends.20in.20the.20wrong.20state) and to better describe the issue Michael wrote: "So the fix is to write the microservices so that they follow the RESTAT protocol correctly - in particular in the method SRAParticipant.java#updateState the switch statement needs to check for TransactionPrepared and return 200 if it is able to prepare the work". Link to the Specification code is https://github.com/jbosstm/narayana/blob/4d7327a7124b54f46814e2102cf10bee6fa44f42/rts/at/tx/src/test/java/org/jboss/jbossts/star/test/SpecTest.java where you can find the valid return codes. Since this demo will be moved in the quickstart repo it is up to you to review the README here or in the issue https://issues.redhat.com/browse/JBTM-3462. When reviewing the README could I ask you to add there also the expected output (i.e. in my terminal the sra-participant logs `SRA: 0_ffff7f000001_83ccf69_645a0fa1_69: Updating hotel participant state to: TransactionPreparedSRA: 0_ffff7f000001_83ccf69_645a0fa1_69: Updating trip participant state to: TransactionPreparedSRA: 0_ffff7f000001_83ccf69_645a0fa1_69: Updating trip participant state to: TransactionCommittedSRA: 0_ffff7f000001_83ccf69_645a0fa1_69: Updating hotel participant state to: TransactionCommitted`)?

FYI I cannot see where those log messages are generated from but they are referring to the names for the RESTAT transaction status. Can you check and update the message to be `TransactionCommitted` rather than `TransactionCommittedSRA` etc - valid status properties are defined in secion `2.3.8 Statuses` (https://github.com/jbosstm/documentation/blob/main/rts/docs/RESTAT-v2-latest.pdf)

**Comment by moulalis** [comment]
> > Thanks @moulalis for your PR. For giving a little bit of context this issue was discussed on zulip (https://narayana.zulipchat.com/#narrow/stream/323715-developers/topic/JBTM-3489-REST-AT.20annotation.20demo.20ends.20in.20the.20wrong.20state) and to better describe the issue Michael wrote: "So the fix is to write the microservices so that they follow the RESTAT protocol correctly - in particular in the method SRAParticipant.java#updateState the switch statement needs to check for TransactionPrepared and return 200 if it is able to prepare the work". Link to the Specification code is https://github.com/jbosstm/narayana/blob/4d7327a7124b54f46814e2102cf10bee6fa44f42/rts/at/tx/src/test/java/org/jboss/jbossts/star/test/SpecTest.java where you can find the valid return codes. Since this demo will be moved in the quickstart repo it is up to you to review the README here or in the issue https://issues.redhat.com/browse/JBTM-3462. When reviewing the README could I ask you to add there also the expected output (i.e. in my terminal the sra-participant logs `SRA: 0_ffff7f000001_83ccf69_645a0fa1_69: Updating hotel participant state to: TransactionPreparedSRA: 0_ffff7f000001_83ccf69_645a0fa1_69: Updating trip participant state to: TransactionPreparedSRA: 0_ffff7f000001_83ccf69_645a0fa1_69: Updating trip participant state to: TransactionCommittedSRA: 0_ffff7f000001_83ccf69_645a0fa1_69: Updating hotel participant state to: TransactionCommitted`)?
> 
> FYI I cannot see where those log messages are generated from but they are referring to the wrong names for the RESTAT transaction status. Can you check and update the message to be `TransactionCommitted` rather than `TransactionCommittedSRA` etc - valid status properties are defined in section `2.3.8 Statuses` of the specification (https://github.com/jbosstm/documentation/blob/main/rts/docs/RESTAT-v2-latest.pdf)

This is already fixed by [PR](https://github.com/jbosstm/quickstart/pull/434/files#diff-797e96a683a64e4abd326f3017f08928d2e4f6904f0660e24f2644602b4afc23R78)

Marco dont that changes at his local.

**Comment by marcosgopen** [comment]
> > Thanks @moulalis for your PR. For giving a little bit of context this issue was discussed on zulip (https://narayana.zulipchat.com/#narrow/stream/323715-developers/topic/JBTM-3489-REST-AT.20annotation.20demo.20ends.20in.20the.20wrong.20state) and to better describe the issue Michael wrote: "So the fix is to write the microservices so that they follow the RESTAT protocol correctly - in particular in the method SRAParticipant.java#updateState the switch statement needs to check for TransactionPrepared and return 200 if it is able to prepare the work". Link to the Specification code is https://github.com/jbosstm/narayana/blob/4d7327a7124b54f46814e2102cf10bee6fa44f42/rts/at/tx/src/test/java/org/jboss/jbossts/star/test/SpecTest.java where you can find the valid return codes. Since this demo will be moved in the quickstart repo it is up to you to review the README here or in the issue https://issues.redhat.com/browse/JBTM-3462. When reviewing the README could I ask you to add there also the expected output (i.e. in my terminal the sra-participant logs `SRA: 0_ffff7f000001_83ccf69_645a0fa1_69: Updating hotel participant state to: TransactionPreparedSRA: 0_ffff7f000001_83ccf69_645a0fa1_69: Updating trip participant state to: TransactionPreparedSRA: 0_ffff7f000001_83ccf69_645a0fa1_69: Updating trip participant state to: TransactionCommittedSRA: 0_ffff7f000001_83ccf69_645a0fa1_69: Updating hotel participant state to: TransactionCommitted`)?
> 
> FYI I cannot see where those log messages are generated from but they are referring to the wrong names for the RESTAT transaction status. Can you check and update the message to be `TransactionCommitted` rather than `TransactionCommittedSRA` etc - valid status properties are defined in section `2.3.8 Statuses` of the specification (https://github.com/jbosstm/documentation/blob/main/rts/docs/RESTAT-v2-latest.pdf)

FYI it is a missing \n , the `SRA` should go in the next line. I had already reviewed it to Moulali in [here](https://github.com/jbosstm/quickstart/pull/434#discussion_r1163857712)

**Comment by marcosgopen** [comment]
> > Thanks @moulalis for your PR. For giving a little bit of context this issue was discussed on zulip (https://narayana.zulipchat.com/#narrow/stream/323715-developers/topic/JBTM-3489-REST-AT.20annotation.20demo.20ends.20in.20the.20wrong.20state) and to better describe the issue Michael wrote: "So the fix is to write the microservices so that they follow the RESTAT protocol correctly - in particular in the method SRAParticipant.java#updateState the switch statement needs to check for TransactionPrepared and return 200 if it is able to prepare the work". Link to the Specification code is https://github.com/jbosstm/narayana/blob/4d7327a7124b54f46814e2102cf10bee6fa44f42/rts/at/tx/src/test/java/org/jboss/jbossts/star/test/SpecTest.java where you can find the valid return codes. Since this demo will be moved in the quickstart repo it is up to you to review the README here or in the issue https://issues.redhat.com/browse/JBTM-3462. When reviewing the README could I ask you to add there also the expected output (i.e. in my terminal the sra-participant logs `SRA: 0_ffff7f000001_83ccf69_645a0fa1_69: Updating hotel participant state to: TransactionPreparedSRA: 0_ffff7f000001_83ccf69_645a0fa1_69: Updating trip participant state to: TransactionPreparedSRA: 0_ffff7f000001_83ccf69_645a0fa1_69: Updating trip participant state to: TransactionCommittedSRA: 0_ffff7f000001_83ccf69_645a0fa1_69: Updating hotel participant state to: TransactionCommitted`)?
> 
> FYI I cannot see where those log messages are generated from but they are referring to the wrong names for the RESTAT transaction status. Can you check and update the message to be `TransactionCommitted` rather than `TransactionCommittedSRA` etc - valid status properties are defined in section `2.3.8 Statuses` of the specification (https://github.com/jbosstm/documentation/blob/main/rts/docs/RESTAT-v2-latest.pdf)

FYI it is a missing \n , the `SRA` should go in the next line. I had already reviewed it to Moulali in [here](https://github.com/jbosstm/quickstart/pull/434#discussion_r1163857712)

**Comment by mmusgrov** [comment]
> Thanks @moulalis for your PR. For giving a little bit of context this issue was discussed on zulip (https://narayana.zulipchat.com/#narrow/stream/323715-developers/topic/JBTM-3489-REST-AT.20annotation.20demo.20ends.20in.20the.20wrong.20state) and to better describe the issue Michael wrote: "So the fix is to write the microservices so that they follow the RESTAT protocol correctly - in particular in the method SRAParticipant.java#updateState the switch statement needs to check for TransactionPrepared and return 200 if it is able to prepare the work". Link to the Specification code is https://github.com/jbosstm/narayana/blob/4d7327a7124b54f46814e2102cf10bee6fa44f42/rts/at/tx/src/test/java/org/jboss/jbossts/star/test/SpecTest.java where you can find the valid return codes. Since this demo will be moved in the quickstart repo it is up to you to review the README here or in the issue https://issues.redhat.com/browse/JBTM-3462. When reviewing the README could I ask you to add there also the expected output (i.e. in my terminal the sra-participant logs `SRA: 0_ffff7f000001_83ccf69_645a0fa1_69: Updating hotel participant state to: TransactionPreparedSRA: 0_ffff7f000001_83ccf69_645a0fa1_69: Updating trip participant state to: TransactionPreparedSRA: 0_ffff7f000001_83ccf69_645a0fa1_69: Updating trip participant state to: TransactionCommittedSRA: 0_ffff7f000001_83ccf69_645a0fa1_69: Updating hotel participant state to: TransactionCommitted`)?

FYI I cannot see where those log messages are generated from but they are referring to the names for the RESTAT transaction status. Can you check and update the message to be `TransactionCommitted` rather than `TransactionCommittedSRA` etc - valid status properties are defined in secion `2.3.8 Statuses` (https://github.com/jbosstm/documentation/blob/main/rts/docs/RESTAT-v2-latest.pdf)

> > 
> 
> Hi @marcosgopen I've already updated the README in https://issues.redhat.com/browse/JBTM-3462 and [PR](https://github.com/jbosstm/quickstart/pull/434/files#diff-4f19a89bb38688ea426851c9baaadd98181c4e978d64014601539874ed88ca5fR32)

I agree, the README change needs to accompany PR https://github.com/jbosstm/quickstart/pull/434 and the latest updated format looks good, thanks for that Moulalis, though I haven't ran through the instructions yet.

**Review by mmusgrov — APPROVED** [review]

**Pull request merged**
