### PR TITLE
[JBEAP-20309] JBTM-3361 - recovery for non-unique xids

### PR DESCRIPTION
**Pull request by ivassile**
JBEAP (7.3.x): https://issues.redhat.com/browse/JBEAP-20309
Upstream: https://issues.redhat.com/browse/JBTM-3361
Upstream PR: https://github.com/jbosstm/narayana/pull/1675, https://github.com/jbosstm/narayana/pull/1679 and https://github.com/jbosstm/narayana/pull/1681

XTS AS_TESTS
!CORE !QA_JTA !QA_JTS_JDKORB !QA_JTS_OPENJDKORB !QA_JTS_JACORB !BLACKTIE !PERF NO_WIN !RTS !AS_TESTS !TOMCAT !JACOCO !LRA

### CODE REVIEW

**Comment by ivassile** [comment]
@mmusgrov Backported JBTM-3361 fix from master to 5.9 (EAP 7.3.x). Didn't port the system property change [1] for the patch, but I can modify this PR to include it. 

[1] https://github.com/jbosstm/narayana/pull/1684/commits/8eacdefdc09b46b3d83940ef744b59d1a998c753

**Comment by mmusgrov** [comment]
TESTIT

**Comment by mmusgrov** [comment]
That's great @ivassile . It does seem like people want the fix disabled by default so the property will be required.
I have triggered a CI run of your PR.

I had to add [extra commits](https://github.com/jbosstm/narayana/pull/1684/commits) to the 4.17 branch. I will compare yours with the ones on that branch to see if we need them but let's wait for the CI run as well.

**Comment by ivassile** [comment]
@mmusgrov Sounds good. Let me know what needs to be added and I'll modify it.

**Comment by ivassile** [comment]
@mmusgrov Just pushed the system property change.

**Review by mmusgrov — APPROVED** [review]
The changes look good and the XTS and MAIN profile tests passed.

**Comment by mmusgrov** [comment]
Thanks @ivassile for the back port.

**Pull request merged**
