### PR TITLE
JBTM-3238 Coordinator#completeNestedLRA and Coordinator#compensateNes…

### PR DESCRIPTION
**Pull request by xstefank**
…tedLRA should return ParticipantStatus

https://issues.redhat.com/browse/JBTM-3238

!QA_JTA !QA_JTS_JDKORB !QA_JTS_OPENJDKORB !QA_JTS_JACORB !BLACKTIE !XTS !PERF NO_WIN !AS_TESTS !TOMCAT !JACOCO !mysql !postgres !db2 !oracle !RTS !MAIN LRA

### CODE REVIEW

**Comment by xstefank** [comment]
@tomjenkinson yes. A simple change, I just missed these two methods on my side.

**Comment by mmusgrov** [comment]
@tomjenkinson This PR satisfies an MP-LRA spec change and there is already a TCK test for it.

**Comment by mmusgrov** [comment]
@xstefank Is it okay to merge this PR?

**Comment by mmusgrov** [comment]
@tomjenkinson thanks for the question. You are correct, none of the TCK tests in 1.0-RC1 would uncover this bug.
@xstefank we need a test for this change. Are there any tests that show that the original behaviour produced incorrect behaviour. Would the test 
`testForgetCalledForNestedParticipantsWhenParentIsClosed` that you added to the LRA branch exercise this bug?

**Comment by xstefank** [comment]
@mmusgrov @tomjenkinson I checked the availability of test for this issue, however, it isn't going to be that easy. I ran into this issue while testing something different and I am not able to reproduce the error again. The code that can run into this issue is in [1] which is hard to hit since INTERNAL_SERVER_ERROR on our Coordinator side is hard to reproduce. I can try to write a test for the previous fix which was fixing the return value of nested Status calls -- this should be easier as it only means that nested LRA should get into Cancelling/Closing state so the parent LRA will call its status. However, I will open a new issue for this and I will not make it a priority right now if you don't mind. There are some more prompt issues at hand on my side. However, return values should be fixed even if we can only conditionally run into this issue I think. Would this be an acceptable resolution?

[1] https://github.com/jbosstm/narayana/blob/master/rts/lra/lra-coordinator-jar/src/main/java/io/narayana/lra/coordinator/domain/model/LRARecord.java#L342

**Comment by mmusgrov** [comment]
The status code that is being returned is clearly following the wrong model and the fix is straight forward. Personally I think not having a test for this is okay and we can add it when we expose the status method via the client API that will be introduced in MP-LRA 1.x

So @tomjenkinson I am going to approve this PR - but let us know if you feel we can't merge without the test?

**Comment by mmusgrov** [comment]
>   . @mmusgrov I also noted the comment that 412 was probably not the correct code, is that comment stale or if not can we get a JBTM for that too please?

@tomjenkinson The comment is referring to the HTTP status code for an LRA but since we deferred the LRA Client API to a later release we can pick any status code that makes sense in a REST setting. When/if we do an client API we should choose/debate which status code to use.

**Comment by mmusgrov** [comment]
@tomjenkinson The JBTM for the test is https://issues.redhat.com/browse/JBTM-3241

**Pull request merged**
