### PR TITLE
JBTM-2978 Compensation should not be considered done in case of network error

### PR DESCRIPTION
**Pull request by mmusgrov**
https://issues.jboss.org/browse/JBTM-2978

!TOMCAT !RTS !QA_JTA !QA_JTS_JDKORB !QA_JTS_OPENJDKORB !QA_JTS_JACORB !BLACKTIE !XTS !PERF !AS_TESTS !mysql !postgres !db2 !oracle

### CODE REVIEW

**Comment by mmusgrov** [comment]
Thanks, I have added the request for a test to my todo list or are you asking for one before approving this PR (the test is manual at the moment and is documented on the JIRA).

**Comment by ochaloup** [comment]
I think it would be good to have a test as part of this PR I thought. But if the fix is urgent then it's probably ok to postpone it.

**Comment by mmusgrov** [comment]
@ochaloup I created https://issues.jboss.org/browse/JBTM-3023 for the test to be added to the automated test suite.

**Comment by ochaloup** [comment]
@mmusgrov : my personal feeling is that the test should be automated as part of this PR.

**Comment by mmusgrov** [comment]
@ochaloup I need the code I added to lra-test in PR #1319 so I am copying it over to this PR. This will produce extra diffs but I will highlight what the extra test is.

**Comment by mmusgrov** [comment]
@ochaloup I think pulling in the code will cause merge problems with the other two outstanding related PRs so I will wait for you to review the tests I added for the other PRs first.

**Comment by mmusgrov** [comment]
@ochaloup  the test for this is SpecIT#connectionHangup
It took a while because the test surfaced a number of issues (that the manual test did not expose) around retries after a broken connection to the participant. So thanks for insisting on the automated test.

**Pull request merged**
