### PR TITLE
JBTM-3713 Upgrade jakarta.transaction-api from 2.0.0 to 2.0.1 in ArjunaJTA/narayana-jta-jakarta/pom.xml

### PR DESCRIPTION
**Pull request by chengfang**
https://issues.redhat.com/browse/JBTM-3713

To Test
JDK17 CORE QA_JTA
Skipped
!TOMCAT !AS_TESTS !RTS !JACOCO !XTS !QA_JTS_OPENJDKORB !PERF !LRA !DB_TESTS !mysql !db2 !postgres !oracle

### CODE REVIEW

**Comment by jmfinelli** [comment]
TESTIT

**Comment by mmusgrov** [comment]
@jmfinelli will you also apply this change to our jakarta native branch please

**Comment by jmfinelli** [comment]
No problem @mmusgrov +1

**Review by jmfinelli — APPROVED** [review]
Thanks @chengfang

**Pull request merged**
