### PR TITLE
JBTM-3376 clean CMR integration test 4.17

### PR DESCRIPTION
**Pull request by ochaloup**
https://issues.redhat.com/browse/JBTM-3376

Making the test working on older WildFly app servers.
Making the test better in way of understanding the failures.

!MAIN AS_TESTS
!QA_JTS_JACORB !QA_JTA !XTS !QA_JTS_JDKORB

### CODE REVIEW

**Review by mmusgrov — APPROVED** [review]
Approving. I must admit I didn't fully understand the impact of the changes, do you think we accidentally back ported the CMR config file at some point in the past?

This PR fixes the failure on the AS_TESTS axis but that axis did not run for this PR since the  btny-pulls-narayana-417 jenkins job does not include the AS_TESTS axis. Do you think we should add the axis to that job?

**Comment by ochaloup** [comment]
@mmusgrov the `AS_TESTS` is run with the EAP6.x job.
Regarding this change the there is no much sense to add the `AS_TESTS` axis to the 4.17 upstream job as the CMR functionality was not integrated with jboss as 7.2.0. If you think I can add the `AS_TESTS` axis to the job but I will still need to disable the CMR testing for the jboss-as 7.2.0 as the CMR test will be failing.

**Comment by ochaloup** [comment]
There is a strange failure in the test. It seems to be related with timing but I need to check in details.

```
Running com.hp.mwtests.ts.jta.commitmarkable.integration.CMRIntegrationTest
Tests run: 1, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 28.912 sec <<< FAILURE!

Results :
Failed tests:   testCMR(com.hp.mwtests.ts.jta.commitmarkable.integration.CMRIntegrationTest): expected:<100> but was:<99>
```

**Comment by ochaloup** [comment]
I'm merging this as from what I can see from the testing and rerunning on the CI this seems to be a intermittent failure not a functionality issue.

**Pull request merged**
