### PR TITLE
[JBTM-2203] Remove ReentrantLock from StateManager

### PR DESCRIPTION
**Pull request by mmusgrov**
Resurrection of PR 680 originally raised by @jesperpedersen 

!RTS !XTS !BLACKTIE !QA_JTS_JDKORB !QA_JTS_JACORB !QA_JTS_OPENJDKORB !MAIN !AS_TESTS NO_WIN !QA_JTA

### CODE REVIEW

**Comment by nmcl** [comment]
The JIRA even says "rejected" (from 2016) so why is this being worked on? At least keep things in sync!

**Comment by mmusgrov** [comment]
There was a bug in the performance comparison checker

**Comment by nmcl** [comment]
OK but that doesn't explain why the JIRA is still closed (rejected). Either the issue is being worked on or it isn't. This isn't a heisenbug ;) It can't be in two states simultaneously until one of us looks at it and the waveform then collapses ;)

**Comment by mmusgrov** [comment]
Well we wanted to do a quick test to test first ie not actually change any code. If we saw a change then that would be the trigger to reopen the JIRA.

**Comment by nmcl** [comment]
So you're doing work against a closed JIRA because ..? It's not hard to click "re-open" you know :)

**Comment by jesperpedersen** [comment]
@mmusgrov !

**Comment by mmusgrov** [comment]
@jesperpedersen Sorry I was setting up a PR poller job on our upshift installation. I temporarily added a build periodically schedule and it started testing all the PRs. Sorry about that. It is disabled now

**Pull request closed without merging**
