### PR TITLE
[JBTM:3785] Upgrade Servlet API from 5.0.0 to 6.0.0 in the BOM

### PR DESCRIPTION
**Pull request by moulalis**
Issue: https://issues.redhat.com/browse/JBTM-3785

CORE TOMCAT AS_TESTS RTS !JACOCO XTS QA_JTA !QA_JTS_OPENJDKORB !PERFORMANCE LRA !DB_TESTS

jmfinelli: Testing axis modified

### CODE REVIEW

**Comment by mmusgrov** [comment]
@moulalis Hello, I noticed that the CORE profile is failing with `NoClassDefFoundError: jakarta/servlet/SingleThreadModel` which seems related, will you be able to find out what's causing it?

**Comment by moulalis** [comment]
> @moulalis Hello, I noticed that the CORE profile is failing with `NoClassDefFoundError: jakarta/servlet/SingleThreadModel` which seems related, will you be able to find out what's causing it?

Sure I will look into it.

**Comment by moulalis** [comment]
@mmusgrov 

Removals, deprecations or backwards incompatible changes

Issue 225 Deprecated wrapped response handling in the doHead method in favour of container implementation of HEAD method behavior
Remove API classes and methods that were deprecated in Servlet 5.0 and earlier. This includes removing the SingleThreadModel and HttpSessionContext interfaces and the HttpUtils class as well as various deprecated methods. There is not that class in the new api So dependencies that are expecting it fail i.e. undertow.

https://mvnrepository.com/artifact/io.undertow/undertow-servlet/2.3.7.Final

I can see last version is using servlet api 6, which is good to know.

Have to check if resteasy-undertow last version is using servlet 6. Will investigate it more and update.

Thanks.

**Comment by mmusgrov** [comment]
Ah, right. Good info, thanks for digging into it.

**Comment by marcosgopen** [comment]
Please @moulalis could you retest it upgrading the resteasy version to 6.2.5.Final and removing these 2 lines: https://github.com/jbosstm/narayana/blob/main/rts/at/tx/pom.xml#L27-L28. These line are not needed anymore since all dependencies would use servlet api 6.0

**Comment by mmusgrov** [comment]
@moulalis Is there any update on this PR?

**Comment by mmusgrov** [comment]
@moulalis does this PR need the `Hold` label on it?

**Comment by moulalis** [comment]
> @moulalis does this PR need the `Hold` label on it?

I will put a hold label until Investigated.

**Comment by moulalis** [comment]
> Please @moulalis could you retest it upgrading the resteasy version to 6.2.5.Final and removing these 2 lines (https://github.com/jbosstm/narayana/blob/main/rts/at/tx/pom.xml#L27-L28) and this line (https://github.com/jbosstm/narayana/blob/main/rts/at/tx/pom.xml#L51) . These lines are not needed anymore since all dependencies would use servlet api 6.0

Hi @mmusgrov @marcosgopen I've just updated PR to above changes, could you please trigger CI tests?

**Comment by mmusgrov** [comment]
@marcosgopen do you think that we can merge this PR now?

**Pull request merged**
