### PR TITLE
[JBTM-3530] no Weld classloading error logs at lra/basic FailedLRAIT

### PR DESCRIPTION
**Pull request by ochaloup**
https://issues.redhat.com/browse/JBTM-3530

LRA
!MAIN !CORE !QA_JTA !QA_JTS_JDKORB !QA_JTS_OPENJDKORB !QA_JTS_JACORB !BLACKTIE !XTS !PERF NO_WIN !RTS !AS_TESTS !TOMCAT !JACOCO

### CODE REVIEW

**Review by mmusgrov — APPROVED** [review]

**Comment by jmfinelli** [comment]
Unfortunately, there is not a way to tell Arquillian to avoid appending the test class to the deployed archive (even though the class is annotated with `@RunAsClient`). Yeah, agree with you, appending the `TestBase` is the only solution to get rid of the WARN. Thanks Ondra for fixing this

**Review by jmfinelli — APPROVED** [review]

**Review by mayankkunwar — APPROVED** [review]

**Review by xstefank — APPROVED** [review]
you can try also `testable = false` in `@Deployment` annotation but I don't see big issues with this solution.

**Comment by jmfinelli** [comment]
@xstefank Tried it already but no luck. It seems that Arquillian appends the test class a priori

**Comment by ochaloup** [comment]
Thanks @jmfinelli for the elaboration and @xstefank for the tip.
I tried with the `testable` and looking about the `RunAsClient` and I don't understand why the testcase is loaded. Maybe because of `@Before` or `@BeforeClass` methods?
Anyway, this fix seems to me the easiest one as Manuel said.

I'm going to merge this.

**Pull request merged**
