### PR TITLE
[JBTM-3611] Add a jakarta-direct.properties for text strings that nee…

### PR DESCRIPTION
**Pull request by jamezp**
…d to be transformed.

https://issues.redhat.com/browse/JBTM-3611

Note that there are other modules that transform byte code. However, in WildFly these were the only ones that were causing issues. If we feel these changes should go into all the transformed modules please let me know and I'll make the changes.

### CODE REVIEW

**Comment by zhfeng** [comment]
TESTIT

**Comment by jmfinelli** [comment]
TESTIT

**Review by mmusgrov — APPROVED** [review]
Thanks very much @jamezp, I will arrange for a new narayana release and WFLY component upgrade PR early next week (we have two other issues I'd like to get into the release but I'd expect those to be done towards the middle of the week but if not then I will do a release anyway).

**Comment by jamezp** [comment]
Okay, excellent. Thanks @mmusgrov! Just as an FYI I filed a WFLY upgrade issue already https://issues.redhat.com/browse/WFLY-16496.

**Pull request merged**
