### PR TITLE
JBTM-3795 recover memory when an LRA terminates

### PR DESCRIPTION
**Pull request by mmusgrov**
https://issues.redhat.com/browse/JBTM-3795

LRA

### CODE REVIEW

**Review by xstefank — APPROVED** [review]
@mmusgrov I tried the camel reproducer and even with your PR, I can't get it working past the eventual coordinator kill after ~1000 requests. I still think this fix is good, but can someone else please try the reproducer?

**Comment by marcosgopen** [comment]
> @mmusgrov I tried the camel reproducer and even with your PR, I can't get it working past the eventual coordinator kill after ~1000 requests. I still think this fix is good, but can someone else please try the reproducer?

I am checking it.

**Comment by mmusgrov** [comment]
Thanks both of you. The camel failure should not stall this PR mind since this PR address a specific issue.

**Comment by zhfeng** [comment]
@xstefank I'm interested with the camel reproducer and is it possible to share?

**Pull request merged**
