### PR TITLE
JBTM-2842 : missing a jboss logging internationalization

### PR DESCRIPTION
**Pull request by rpelisse**
Issue: [JBEAP-8290](https://issues.jboss.org/browse/JBEAP-8290)
Upstream Issue: [JBTM-2842](https://issues.jboss.org/browse/JBTM-2842)

### CODE REVIEW

**Comment by gytis** [comment]
I think this message should be located here https://github.com/wildfly/wildfly/blob/master/xts/src/main/java/org/jboss/as/xts/logging/XtsAsLogger.java and committed to WildFly.

**Comment by gytis** [comment]
Unless I misunderstood and you're not going to use it here: https://github.com/wildfly/wildfly/blob/master/xts/src/main/java/org/jboss/as/xts/GracefulShutdownRejectionRule.java#L45

**Comment by rpelisse** [comment]
Yes, exactly, I'm want to use it in the submodule, and I somehow did NOT see the XtsasLogger class, and went straight to JBossTS, my bad. I'll move the message to XtsAsLogger and thus closing this PR.

**Comment by gytis** [comment]
Thanks, @rpelisse

**Pull request closed without merging**
