### PR TITLE
JBTM-2798 Added testcase for directly closing a connection and isClos…

### PR DESCRIPTION
**Pull request by pms1**
…ed after closing

!XTS !BLACKTIE !QA_JTA !QA_JTS_JDKORB !PERF

### CODE REVIEW

**Comment by pms1** [comment]
@tomjenkinson CLA was signed

**Comment by gytis** [comment]
@pms1 , there are test failures in CI

> Running com.hp.mwtests.ts.jdbc.basic.JDBC2Test
Tests run: 3, Failures: 1, Errors: 1, Skipped: 0, Time elapsed: 0.289 sec <<< FAILURE! - in com.hp.mwtests.ts.jdbc.basic.JDBC2Test
testCloseUnused(com.hp.mwtests.ts.jdbc.basic.JDBC2Test)  Time elapsed: 0.079 sec  <<< ERROR!
java.lang.NullPointerException
	at com.hp.mwtests.ts.jdbc.basic.JDBC2Test.testCloseUnused(JDBC2Test.java:337)
testCloseUsed(com.hp.mwtests.ts.jdbc.basic.JDBC2Test)  Time elapsed: 0.001 sec  <<< FAILURE!
java.lang.AssertionError
	at com.hp.mwtests.ts.jdbc.basic.JDBC2Test.testCloseUsed(JDBC2Test.java:352)
Running com.hp.mwtests.ts.jdbc.basic.JDBC3Test
Tests run: 7, Failures: 1, Errors: 1, Skipped: 0, Time elapsed: 0.324 sec <<< FAILURE! - in com.hp.mwtests.ts.jdbc.basic.JDBC3Test
testCloseUnused(com.hp.mwtests.ts.jdbc.basic.JDBC3Test)  Time elapsed: 0.003 sec  <<< ERROR!
java.lang.NullPointerException
testCloseUsed(com.hp.mwtests.ts.jdbc.basic.JDBC3Test)  Time elapsed: 0 sec  <<< FAILURE!
java.lang.AssertionError

**Comment by pms1** [comment]
@gytis Is there any chance for me to see the details of those tests? Locally the whole test suite runs fine. Somehow, the results that you quoted seem to be from the first version of the pull request that just contained the new test cases, but no fix.

**Comment by gytis** [comment]
@pms1 I'll trigger a CI build again just to be sure.

**Comment by gytis** [comment]
@pms1 , all seems to work fine. Could you please squash your commits and I'll merge them in.

**Comment by pms1** [comment]
@gytis Commits have been squashed

**Pull request merged**
