### PR TITLE
JBTM-3448 update dependencies for jdk-16 build.

### PR DESCRIPTION
**Pull request by jhalliday**
https://issues.redhat.com/browse/JBTM-3448

MAIN CORE TOMCAT AS_TESTS RTS JACOCO XTS QA_JTA QA_JTS_JACORB QA_JTS_JDKORB QA_JTS_OPENJDKORB BLACKTIE PERF LRA !NO_WIN DB_TESTS mysql db2 postgres oracle

### CODE REVIEW

**Comment by mmusgrov** [comment]
Looks good but why a full CI test run of everything given that we don't test with jdk-16?

**Comment by jhalliday** [comment]
> Looks good but why a full CI test run of everything given that we don't test with jdk-16?

Because I don't test on anything but 16, so I've no idea about possible regressions.

**Comment by mmusgrov** [comment]
My point is that we only have JDK 8 and 11 on AMS so the full CI run will not prove anything.

**Review by mmusgrov — APPROVED** [review]
The main narayana job passed.
@jhalliday Do you want to wait for the rest to pass too ;-) or should I merge now?

**Comment by jhalliday** [comment]
Merge it if you're happy, the other runs probably didn't survive the CI server rebuild anyhow.

**Pull request merged**
