### PR TITLE
JBTM-3561 Remove old unused private code (ArjunaCore)

### PR DESCRIPTION
**Pull request by boris-unckel**
Fixes https://issues.redhat.com/browse/JBTM-3561

Remove

- unused imports
- empty statements
- unused private methods
- unused private fields
- commented code (not doc)
- duplicated braces (no beautifying)

CORE TOMCAT AS_TESTS RTS JACOCO XTS QA_JTA QA_JTS_JACORB QA_JTS_JDKORB QA_JTS_OPENJDKORB PERF LRA !NO_WIN DB_TESTS mysql db2 postgres oracle

### CODE REVIEW

**Comment by boris-unckel** [comment]
Hello @mmusgrov this is my first PR for narayana. I hope it matches to the formal requirements. Could you  check and give feedback, please? If everything is OK it would be great to get a CI run.

**Comment by jmfinelli** [comment]
TESTIT

**Comment by boris-unckel** [comment]
@jmfinelli My local test was `./build.sh install -am -pl :arjunacore` and successful. I don't have access to RedHats network, so I can't see the CI log and no error message. All tests fail quite fast - is there any checkstyle or something which is not included by default in build.sh?

**Comment by jmfinelli** [comment]
> @jmfinelli My local test was `./build.sh install -am -pl :arjunacore` and successful. I don't have access to RedHats network, so I can't see the CI log and no error message. All tests fail quite fast - is there any checkstyle or something which is not included by default in build.sh?

To test Narayana locally, you can use `./scripts/hudson/narayana.sh`, which runs most of the `profiles` mentioned [here](https://github.com/jbosstm/narayana/blob/master/PULL_REQUEST_TEMPLATE.md). For example, to test Narayana with the  `CORE` profile, you can run `WORKSPACE=$(pwd) PROFILE=CORE ./scripts/hudson/narayana.sh`. As you do not have access to the Red Hat network, you will not be able to run tests against DBs out-of-the-box (e.g. the `QA_JTA` profile). If you still want to run those tests, you should spin up your DBs locally and instruct Narayana to use them.

**Comment by boris-unckel** [comment]
@jmfinelli Thank you. It works and directly the CORE profile found a compile error, not visible by simply running the build.sh.

**Review by mmusgrov — COMMENTED** [review]
Our policy is not to accept PRs whose only purpose is to clean up the code base, they make it difficult to track the history of features and bug fixes. 

The only circumstance under which we allow such code clean up is if the file in question is being modified as part of a fix or a functional enhancement.

I will update the CONTRIBUTING.md file to clarify the contribution process, apologies that the project has not made this explicit.

[Edit] Actually this is mentioned in [CONTRIBUTING.md](https://github.com/jbosstm/narayana/blob/master/CONTRIBUTING.md#before-you-contribute) in item 3 of the list.

**Comment by boris-unckel** [comment]
@mmusgrov I was too fast with `push force`, reading your comment afterwards. OK, I'll withdraw the PR.

**Comment by mmusgrov** [comment]
Hi @boris-unckel thanks for you interest in transactions and I hope you haven't been put off from contributing.
I have been planning for some time now to go through our list of outstanding JIRAs, of which there are many, and adding a field for ones suitable for first time contributors. I will increase the priority of that task.

**Comment by boris-unckel** [comment]
@mmusgrov Thanks for your offer with the JIRAs, I'll check the list.

> [Edit] Actually this is mentioned in CONTRIBUTING.md in item 3 of the list.

Yes, I simply didn't consider "removing unused code" as "formatting". But I'm fine with it - I don't want to start nit-picking here.

Maybe you're checking with another tool, if not the Sonarcloud analysis may be of interest: https://sonarcloud.io/project/issues?id=narayana&resolved=false

Is there a recommendation which profiles you need to run locally for each maven module before you provide a PR? And second which to choose for the CI?

**Pull request closed without merging**
